project_id = "hkgscohedqgxrhmbryww"

[functions.create-xendit-invoice]
verify_jwt = false

[functions.xendit-webhook]
verify_jwt = false

[functions.send-reservation-notification]
verify_jwt = false

[functions.create-doku-checkout]
verify_jwt = false

[functions.doku-webhook]
verify_jwt = false
