project_id = "hkgscohedqgxrhmbryww"

[functions.create-xendit-invoice]
verify_jwt = false

[functions.xendit-webhook]
verify_jwt = false

[functions.send-reservation-notification]
verify_jwt = false

[functions.create-doku-checkout]
verify_jwt = false

[functions.doku-webhook]
verify_jwt = false

[functions.create-qris-payment]
verify_jwt = false

[functions.check-qris-status]
verify_jwt = false

[functions.create-card-payment]
verify_jwt = false

[functions.openai-realtime-session]
verify_jwt = false

[functions.google-analytics]
verify_jwt = false
