import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ru" | "id" | "uk" | "fr" | "hi" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Hero
    "hero.title": "SHISHA",
    "hero.subtitle": "MENU",
    "hero.tagline": "Experience the Art of Smoke",
    
    // Menu
    "menu.ourSelection": "Our Selection",
    "menu.curatedFlavors": "Curated Flavors",
    "menu.singleFlavor": "Single Flavor",
    "menu.signatureMixes": "Signature Mixes",
    "menu.signature": "Signature",
    "menu.addedToCart": "Added to cart!",
    "menu.loginToOrder": "Please login to order",
    "menu.clickToAdd": "Click + to add items to your order",
    "menu.loginToOrderHint": "Login to start ordering",
    "menu.extras": "Extras",
    "menu.extrasSubtitle": "Drinks & Snacks",
    "menu.drinks": "Beverages",
    "menu.snacks": "Snacks",
    "menu.addons": "Add-ons",
    
    // Cart
    "cart.title": "Your Order",
    "cart.empty": "Your cart is empty",
    "cart.total": "Total",
    "cart.placeOrder": "Place Order",
    "cart.clear": "Clear cart",
    "cart.loginRequired": "Please login to place an order",
    "cart.emptyCart": "Your cart is empty",
    "cart.orderSuccess": "Order placed successfully!",
    "cart.orderError": "Failed to place order",
    "cart.loginToOrder": "Please login to place an order",
    "cart.login": "Login",
    "cart.payNow": "Pay Now",
    "cart.payLater": "Pay Later",
    "cart.paymentError": "Payment failed. Please try again.",
    
    // Order Confirmation
    "order.confirmed": "Order Confirmed!",
    "order.thankYou": "Thank you for your order",
    "order.orderNumber": "Order Number",
    "order.estimatedTime": "Estimated Wait Time",
    "order.approx": "Approx.",
    "order.minutes": "minutes",
    "order.summary": "Order Summary",
    "order.backToMenu": "Back to Menu",
    "order.viewProfile": "View Profile",
    "order.notification": "We'll notify you when your order is ready",
    "order.deliveryTo": "Delivery to room",
    "order.wrongRoom": "If the room number is incorrect, please update it",
    "order.updateRoom": "Update room number",
    "order.noRoom": "Room number not specified",
    "order.addRoomHint": "Add your room number for delivery",
    "order.addRoom": "Add room number",
    "order.cancelOrder": "Cancel Order",
    "order.cancelling": "Cancelling...",
    "order.cancelled": "Order Cancelled",
    "order.cancelledDesc": "Your order has been cancelled",
    "order.cancelError": "Cancel Error",
    "order.cancelErrorDesc": "Failed to cancel order. Please try again.",
    "order.ready": "Order Ready!",
    "order.readyDesc": "Your order is ready for pickup/delivery",
    
    // Strength levels
    "strength.ultraLight": "Ultra Light",
    "strength.light": "Light",
    "strength.medium": "Medium",
    "strength.boldStrong": "Bold Strong",
    
    // Footer
    "footer.inhale": "Inhale the",
    "footer.moment": "Moment",
    "footer.description": "Each puff tells a story. Let the smoke carry your thoughts as the sunset paints the sky in shades of gold.",
    "footer.tagline": "Premium Shisha Experience",
    
    // Auth
    "auth.login": "Login",
    "auth.profile": "Profile",
    "auth.level": "Lvl.",
    "auth.admin": "Admin",
    "auth.backToHome": "Back to Home",
    "auth.loginTitle": "Login",
    "auth.signupTitle": "Sign Up",
    "auth.loginSubtitle": "Log in to your account",
    "auth.signupSubtitle": "Create a new account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.loginButton": "Log In",
    "auth.signupButton": "Sign Up",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    "auth.terms": "By clicking the button, you agree to the terms of use",
    "auth.invalidEmail": "Invalid email format",
    "auth.passwordMinLength": "Password must be at least 6 characters",
    "auth.loginError": "Login Error",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.error": "Error",
    "auth.welcome": "Welcome!",
    "auth.loginSuccess": "You have successfully logged in",
    "auth.signupError": "Registration Error",
    "auth.userExists": "A user with this email already exists",
    "auth.signupSuccess": "Registration successful!",
    "auth.checkEmail": "Check your email to confirm your account",
    "auth.somethingWrong": "Something went wrong. Please try again later.",
    
    // Admin/Dashboard
    "admin.panel": "Admin Panel",
    "admin.accounting": "Accounting",
    "admin.backToHome": "Back to Home",
    "admin.logout": "Logout",
    "admin.overview": "Overview",
    "admin.orders": "Orders",
    "admin.users": "Users",
    "admin.totalOrders": "Total Orders",
    "admin.pending": "Pending",
    "admin.paid": "Paid",
    "admin.today": "Today",
    "admin.totalRevenue": "Total Revenue",
    "admin.todayRevenue": "Today's Revenue",
    "admin.totalHookahs": "Total Hookahs",
    "admin.totalUsers": "Total Users",
    "admin.currentOrders": "Current Orders",
    "admin.recentOrders": "Recent Orders",
    "admin.allOrders": "All Orders",
    "admin.noOrders": "No orders",
    "admin.hookahs": "hookah(s)",
    "admin.room": "Room",
    "admin.guest": "Guest",
    "admin.markAsPaid": "Mark as Paid",
    "admin.cancel": "Cancel",
    "admin.statusUpdated": "Status Updated",
    "admin.orderPaid": "Order marked as paid",
    "admin.orderCancelled": "Order cancelled",
    "admin.confirmAction": "Confirm Action",
    "admin.confirmPaidMessage": "Are you sure you want to mark this order as paid?",
    "admin.confirmCancelMessage": "Are you sure you want to cancel this order?",
    "admin.confirm": "Confirm",
    "admin.accessDenied": "Access Denied",
    "admin.noPermission": "You don't have permission to access this page",
    "admin.filterAll": "All",
    "admin.filterPending": "Pending",
    "admin.filterPaid": "Paid",
    "admin.filterCancelled": "Cancelled",
    "admin.sortNewest": "Newest",
    "admin.sortOldest": "Oldest",
    "admin.addPurchase": "Add Purchase",
    "admin.hookahCount": "Hookah Count",
    "admin.amount": "Amount",
    "admin.notes": "Notes",
    "admin.optional": "Optional",
    "admin.freeDrink": "Free Drink",
    "admin.freeSnack": "Free Snack",
    "admin.save": "Save",
    "admin.purchaseAdded": "Purchase Added",
    "admin.selectUser": "Select a user",
    "admin.orderHistory": "Order History",
    "admin.noName": "No name",
    "admin.drink": "Drink",
    "admin.snack": "Snack",
    "admin.manageRoles": "Manage Roles",
    "admin.roleAdded": "Role Added",
    "admin.roleRemoved": "Role Removed",
    "admin.search": "Search by email, name or room...",
    "admin.total": "total",
    "admin.exportCsv": "Export CSV",
    "admin.dateRange": "Date Range",
    "admin.revenue": "Revenue",
  },
  ru: {
    "hero.title": "КАЛЬЯН",
    "hero.subtitle": "МЕНЮ",
    "hero.tagline": "Искусство дыма",
    "menu.ourSelection": "Наш выбор",
    "menu.curatedFlavors": "Избранные вкусы",
    "menu.singleFlavor": "Одиночный вкус",
    "menu.signatureMixes": "Фирменные миксы",
    "menu.signature": "Фирменный",
    "menu.addedToCart": "Добавлено в корзину!",
    "menu.loginToOrder": "Войдите, чтобы сделать заказ",
    "menu.clickToAdd": "Нажмите + чтобы добавить в заказ",
    "menu.loginToOrderHint": "Войдите, чтобы начать заказ",
    "menu.extras": "Дополнительно",
    "menu.extrasSubtitle": "Напитки и закуски",
    "menu.drinks": "Напитки",
    "menu.snacks": "Закуски",
    "menu.addons": "Дополнения",
    "cart.title": "Ваш заказ",
    "cart.empty": "Корзина пуста",
    "cart.total": "Итого",
    "cart.placeOrder": "Оформить заказ",
    "cart.clear": "Очистить корзину",
    "cart.loginRequired": "Войдите, чтобы оформить заказ",
    "cart.emptyCart": "Корзина пуста",
    "cart.orderSuccess": "Заказ успешно оформлен!",
    "cart.orderError": "Ошибка оформления заказа",
    "cart.loginToOrder": "Войдите, чтобы оформить заказ",
    "cart.login": "Войти",
    "cart.payNow": "Оплатить сейчас",
    "cart.payLater": "Оплатить позже",
    "cart.paymentError": "Ошибка оплаты. Попробуйте ещё раз.",
    "order.confirmed": "Заказ подтверждён!",
    "order.thankYou": "Спасибо за ваш заказ",
    "order.orderNumber": "Номер заказа",
    "order.estimatedTime": "Ожидаемое время",
    "order.approx": "Примерно",
    "order.minutes": "минут",
    "order.summary": "Состав заказа",
    "order.backToMenu": "Вернуться к меню",
    "order.viewProfile": "Мой профиль",
    "order.notification": "Мы уведомим вас, когда заказ будет готов",
    "order.deliveryTo": "Доставка в комнату",
    "order.wrongRoom": "Если номер комнаты неверный, пожалуйста, обновите его",
    "order.updateRoom": "Изменить номер комнаты",
    "order.noRoom": "Номер комнаты не указан",
    "order.addRoomHint": "Добавьте номер комнаты для доставки",
    "order.addRoom": "Указать номер комнаты",
    "order.cancelOrder": "Отменить заказ",
    "order.cancelling": "Отмена...",
    "order.cancelled": "Заказ отменён",
    "order.cancelledDesc": "Ваш заказ был отменён",
    "order.cancelError": "Ошибка отмены",
    "order.cancelErrorDesc": "Не удалось отменить заказ. Попробуйте ещё раз.",
    "order.ready": "Заказ готов!",
    "order.readyDesc": "Ваш заказ готов к выдаче/доставке",
    "strength.ultraLight": "Ультра лёгкий",
    "strength.light": "Лёгкий",
    "strength.medium": "Средний",
    "strength.boldStrong": "Крепкий",
    "footer.inhale": "Вдохни",
    "footer.moment": "Момент",
    "footer.description": "Каждая затяжка рассказывает историю. Пусть дым унесёт твои мысли, пока закат окрашивает небо в золотые оттенки.",
    "footer.tagline": "Премиум кальянный опыт",
    "auth.login": "Войти",
    "auth.profile": "Профиль",
    "auth.level": "Ур.",
    "auth.admin": "Админ",
    "auth.backToHome": "На главную",
    "auth.loginTitle": "Вход",
    "auth.signupTitle": "Регистрация",
    "auth.loginSubtitle": "Войдите в свой аккаунт",
    "auth.signupSubtitle": "Создайте новый аккаунт",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.loginButton": "Войти",
    "auth.signupButton": "Зарегистрироваться",
    "auth.noAccount": "Нет аккаунта?",
    "auth.haveAccount": "Уже есть аккаунт?",
    "auth.terms": "Нажимая кнопку, вы соглашаетесь с условиями использования",
    "auth.invalidEmail": "Неверный формат email",
    "auth.passwordMinLength": "Пароль должен содержать минимум 6 символов",
    "auth.loginError": "Ошибка входа",
    "auth.invalidCredentials": "Неверный email или пароль",
    "auth.error": "Ошибка",
    "auth.welcome": "Добро пожаловать!",
    "auth.loginSuccess": "Вы успешно вошли в систему",
    "auth.signupError": "Ошибка регистрации",
    "auth.userExists": "Пользователь с таким email уже существует",
    "auth.signupSuccess": "Регистрация успешна!",
    "auth.checkEmail": "Проверьте вашу почту для подтверждения аккаунта",
    "auth.somethingWrong": "Что-то пошло не так. Попробуйте позже.",
    
    // Admin/Dashboard
    "admin.panel": "Админ панель",
    "admin.accounting": "Бухгалтерия",
    "admin.backToHome": "На главную",
    "admin.logout": "Выйти",
    "admin.overview": "Обзор",
    "admin.orders": "Заказы",
    "admin.users": "Пользователи",
    "admin.totalOrders": "Всего заказов",
    "admin.pending": "Ожидают оплаты",
    "admin.paid": "Оплачено",
    "admin.today": "Сегодня",
    "admin.totalRevenue": "Общая выручка",
    "admin.todayRevenue": "Выручка сегодня",
    "admin.totalHookahs": "Всего кальянов",
    "admin.totalUsers": "Пользователей",
    "admin.currentOrders": "Текущие заказы",
    "admin.recentOrders": "Последние заказы",
    "admin.allOrders": "Все заказы",
    "admin.noOrders": "Нет заказов",
    "admin.hookahs": "кальян(ов)",
    "admin.room": "Комната",
    "admin.guest": "Гость",
    "admin.markAsPaid": "Оплачено",
    "admin.cancel": "Отмена",
    "admin.statusUpdated": "Статус обновлён",
    "admin.orderPaid": "Заказ отмечен как оплаченный",
    "admin.orderCancelled": "Заказ отменён",
    "admin.confirmAction": "Подтвердите действие",
    "admin.confirmPaidMessage": "Вы уверены, что хотите отметить этот заказ как оплаченный?",
    "admin.confirmCancelMessage": "Вы уверены, что хотите отменить этот заказ?",
    "admin.confirm": "Подтвердить",
    "admin.accessDenied": "Доступ запрещён",
    "admin.noPermission": "У вас нет прав для доступа к этой странице",
    "admin.filterAll": "Все",
    "admin.filterPending": "Ожидают",
    "admin.filterPaid": "Оплачены",
    "admin.filterCancelled": "Отменены",
    "admin.sortNewest": "Новые",
    "admin.sortOldest": "Старые",
    "admin.addPurchase": "Добавить покупку",
    "admin.hookahCount": "Количество кальянов",
    "admin.amount": "Сумма",
    "admin.notes": "Заметка",
    "admin.optional": "Необязательно",
    "admin.freeDrink": "Бесплатный напиток",
    "admin.freeSnack": "Бесплатный снек",
    "admin.save": "Сохранить",
    "admin.purchaseAdded": "Покупка добавлена",
    "admin.selectUser": "Выберите пользователя",
    "admin.orderHistory": "История заказов",
    "admin.noName": "Без имени",
    "admin.drink": "Напиток",
    "admin.snack": "Снек",
    "admin.manageRoles": "Управление ролями",
    "admin.roleAdded": "Роль добавлена",
    "admin.roleRemoved": "Роль удалена",
    "admin.search": "Поиск по email, имени или комнате...",
    "admin.total": "всего",
    "admin.exportCsv": "Экспорт CSV",
    "admin.dateRange": "Период",
    "admin.revenue": "Выручка",
  },
  id: {
    "hero.title": "SHISHA",
    "hero.subtitle": "MENU",
    "hero.tagline": "Rasakan Seni Asap",
    "menu.ourSelection": "Pilihan Kami",
    "menu.curatedFlavors": "Rasa Terpilih",
    "menu.singleFlavor": "Rasa Tunggal",
    "menu.signatureMixes": "Campuran Khas",
    "menu.signature": "Khas",
    "menu.extras": "Tambahan",
    "menu.extrasSubtitle": "Minuman & Makanan Ringan",
    "menu.drinks": "Minuman",
    "menu.snacks": "Makanan Ringan",
    "menu.addons": "Tambahan",
    "strength.ultraLight": "Ultra Ringan",
    "strength.light": "Ringan",
    "strength.medium": "Sedang",
    "strength.boldStrong": "Kuat",
    "footer.inhale": "Hirup",
    "footer.moment": "Momen",
    "footer.description": "Setiap hisapan menceritakan sebuah kisah. Biarkan asap membawa pikiranmu saat matahari terbenam melukis langit dengan warna emas.",
    "footer.tagline": "Pengalaman Shisha Premium",
    "auth.login": "Masuk",
    "auth.profile": "Profil",
    "auth.level": "Lvl.",
    "auth.admin": "Admin",
    "auth.backToHome": "Kembali ke Beranda",
    "auth.loginTitle": "Masuk",
    "auth.signupTitle": "Daftar",
    "auth.loginSubtitle": "Masuk ke akun Anda",
    "auth.signupSubtitle": "Buat akun baru",
    "auth.email": "Email",
    "auth.password": "Kata Sandi",
    "auth.loginButton": "Masuk",
    "auth.signupButton": "Daftar",
    "auth.noAccount": "Belum punya akun?",
    "auth.haveAccount": "Sudah punya akun?",
    "auth.terms": "Dengan mengklik tombol, Anda menyetujui ketentuan penggunaan",
    "auth.invalidEmail": "Format email tidak valid",
    "auth.passwordMinLength": "Kata sandi minimal 6 karakter",
    "auth.loginError": "Kesalahan Masuk",
    "auth.invalidCredentials": "Email atau kata sandi salah",
    "auth.error": "Kesalahan",
    "auth.welcome": "Selamat Datang!",
    "auth.loginSuccess": "Anda berhasil masuk",
    "auth.signupError": "Kesalahan Pendaftaran",
    "auth.userExists": "Pengguna dengan email ini sudah ada",
    "auth.signupSuccess": "Pendaftaran berhasil!",
    "auth.checkEmail": "Periksa email Anda untuk mengonfirmasi akun",
    "auth.somethingWrong": "Terjadi kesalahan. Silakan coba lagi nanti.",
    
    // Admin/Dashboard
    "admin.panel": "Panel Admin",
    "admin.accounting": "Akuntansi",
    "admin.backToHome": "Kembali ke Beranda",
    "admin.logout": "Keluar",
    "admin.overview": "Ringkasan",
    "admin.orders": "Pesanan",
    "admin.users": "Pengguna",
    "admin.totalOrders": "Total Pesanan",
    "admin.pending": "Menunggu",
    "admin.paid": "Dibayar",
    "admin.today": "Hari Ini",
    "admin.totalRevenue": "Total Pendapatan",
    "admin.todayRevenue": "Pendapatan Hari Ini",
    "admin.totalHookahs": "Total Shisha",
    "admin.totalUsers": "Total Pengguna",
    "admin.currentOrders": "Pesanan Saat Ini",
    "admin.recentOrders": "Pesanan Terbaru",
    "admin.allOrders": "Semua Pesanan",
    "admin.noOrders": "Tidak ada pesanan",
    "admin.hookahs": "shisha",
    "admin.room": "Kamar",
    "admin.guest": "Tamu",
    "admin.markAsPaid": "Tandai Dibayar",
    "admin.cancel": "Batal",
    "admin.statusUpdated": "Status Diperbarui",
    "admin.orderPaid": "Pesanan ditandai dibayar",
    "admin.orderCancelled": "Pesanan dibatalkan",
    "admin.confirmAction": "Konfirmasi Tindakan",
    "admin.confirmPaidMessage": "Apakah Anda yakin ingin menandai pesanan ini sebagai dibayar?",
    "admin.confirmCancelMessage": "Apakah Anda yakin ingin membatalkan pesanan ini?",
    "admin.confirm": "Konfirmasi",
    "admin.accessDenied": "Akses Ditolak",
    "admin.noPermission": "Anda tidak memiliki izin untuk mengakses halaman ini",
    "admin.filterAll": "Semua",
    "admin.filterPending": "Menunggu",
    "admin.filterPaid": "Dibayar",
    "admin.filterCancelled": "Dibatalkan",
    "admin.sortNewest": "Terbaru",
    "admin.sortOldest": "Terlama",
    "admin.addPurchase": "Tambah Pembelian",
    "admin.hookahCount": "Jumlah Shisha",
    "admin.amount": "Jumlah",
    "admin.notes": "Catatan",
    "admin.optional": "Opsional",
    "admin.freeDrink": "Minuman Gratis",
    "admin.freeSnack": "Makanan Gratis",
    "admin.save": "Simpan",
    "admin.purchaseAdded": "Pembelian Ditambahkan",
    "admin.selectUser": "Pilih pengguna",
    "admin.orderHistory": "Riwayat Pesanan",
    "admin.noName": "Tanpa nama",
    "admin.drink": "Minuman",
    "admin.snack": "Makanan",
    "admin.manageRoles": "Kelola Peran",
    "admin.roleAdded": "Peran Ditambahkan",
    "admin.roleRemoved": "Peran Dihapus",
    "admin.search": "Cari berdasarkan email, nama atau kamar...",
    "admin.total": "total",
    "admin.exportCsv": "Ekspor CSV",
    "admin.dateRange": "Rentang Tanggal",
    "admin.revenue": "Pendapatan",
  },
  uk: {
    "hero.title": "КАЛЬЯН",
    "hero.subtitle": "МЕНЮ",
    "hero.tagline": "Відчуй мистецтво диму",
    "menu.ourSelection": "Наш вибір",
    "menu.curatedFlavors": "Вибрані смаки",
    "menu.singleFlavor": "Одиночний смак",
    "menu.signatureMixes": "Фірмові мікси",
    "menu.signature": "Фірмовий",
    "menu.extras": "Додатково",
    "menu.extrasSubtitle": "Напої та закуски",
    "menu.drinks": "Напої",
    "menu.snacks": "Закуски",
    "menu.addons": "Додатки",
    "strength.ultraLight": "Ультра легкий",
    "strength.light": "Легкий",
    "strength.medium": "Середній",
    "strength.boldStrong": "Міцний",
    "footer.inhale": "Вдихни",
    "footer.moment": "Мить",
    "footer.description": "Кожна затяжка розповідає історію. Нехай дим несе твої думки, поки захід сонця малює небо золотими відтінками.",
    "footer.tagline": "Преміум кальянний досвід",
    "auth.login": "Увійти",
    "auth.profile": "Профіль",
    "auth.level": "Рів.",
    "auth.admin": "Адмін",
    "auth.backToHome": "На головну",
    "auth.loginTitle": "Вхід",
    "auth.signupTitle": "Реєстрація",
    "auth.loginSubtitle": "Увійдіть у свій акаунт",
    "auth.signupSubtitle": "Створіть новий акаунт",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.loginButton": "Увійти",
    "auth.signupButton": "Зареєструватися",
    "auth.noAccount": "Немає акаунту?",
    "auth.haveAccount": "Вже є акаунт?",
    "auth.terms": "Натискаючи кнопку, ви погоджуєтесь з умовами використання",
    "auth.invalidEmail": "Невірний формат email",
    "auth.passwordMinLength": "Пароль повинен містити мінімум 6 символів",
    "auth.loginError": "Помилка входу",
    "auth.invalidCredentials": "Невірний email або пароль",
    "auth.error": "Помилка",
    "auth.welcome": "Ласкаво просимо!",
    "auth.loginSuccess": "Ви успішно увійшли в систему",
    "auth.signupError": "Помилка реєстрації",
    "auth.userExists": "Користувач з таким email вже існує",
    "auth.signupSuccess": "Реєстрація успішна!",
    "auth.checkEmail": "Перевірте вашу пошту для підтвердження акаунту",
    "auth.somethingWrong": "Щось пішло не так. Спробуйте пізніше.",
    
    // Admin/Dashboard
    "admin.panel": "Панель адміна",
    "admin.accounting": "Бухгалтерія",
    "admin.backToHome": "На головну",
    "admin.logout": "Вийти",
    "admin.overview": "Огляд",
    "admin.orders": "Замовлення",
    "admin.users": "Користувачі",
    "admin.totalOrders": "Всього замовлень",
    "admin.pending": "Очікують",
    "admin.paid": "Оплачено",
    "admin.today": "Сьогодні",
    "admin.totalRevenue": "Загальний дохід",
    "admin.todayRevenue": "Дохід сьогодні",
    "admin.totalHookahs": "Всього кальянів",
    "admin.totalUsers": "Користувачів",
    "admin.currentOrders": "Поточні замовлення",
    "admin.recentOrders": "Останні замовлення",
    "admin.allOrders": "Всі замовлення",
    "admin.noOrders": "Немає замовлень",
    "admin.hookahs": "кальян(ів)",
    "admin.room": "Кімната",
    "admin.guest": "Гість",
    "admin.markAsPaid": "Оплачено",
    "admin.cancel": "Скасувати",
    "admin.statusUpdated": "Статус оновлено",
    "admin.orderPaid": "Замовлення оплачено",
    "admin.orderCancelled": "Замовлення скасовано",
    "admin.confirmAction": "Підтвердіть дію",
    "admin.confirmPaidMessage": "Ви впевнені, що хочете позначити це замовлення як оплачене?",
    "admin.confirmCancelMessage": "Ви впевнені, що хочете скасувати це замовлення?",
    "admin.confirm": "Підтвердити",
    "admin.accessDenied": "Доступ заборонено",
    "admin.noPermission": "У вас немає прав для доступу до цієї сторінки",
    "admin.filterAll": "Всі",
    "admin.filterPending": "Очікують",
    "admin.filterPaid": "Оплачені",
    "admin.filterCancelled": "Скасовані",
    "admin.sortNewest": "Нові",
    "admin.sortOldest": "Старі",
    "admin.search": "Пошук за email, ім'ям або кімнатою...",
    "admin.total": "всього",
    "admin.exportCsv": "Експорт CSV",
    "admin.revenue": "Дохід",
  },
  fr: {
    "hero.title": "CHICHA",
    "hero.subtitle": "MENU",
    "hero.tagline": "L'Art de la Fumée",
    "menu.ourSelection": "Notre Sélection",
    "menu.curatedFlavors": "Saveurs Raffinées",
    "menu.singleFlavor": "Saveur Unique",
    "menu.signatureMixes": "Mélanges Signature",
    "menu.signature": "Signature",
    "menu.extras": "Extras",
    "menu.extrasSubtitle": "Boissons & Collations",
    "menu.drinks": "Boissons",
    "menu.snacks": "Collations",
    "menu.addons": "Suppléments",
    "strength.ultraLight": "Ultra Léger",
    "strength.light": "Léger",
    "strength.medium": "Moyen",
    "strength.boldStrong": "Corsé",
    "footer.inhale": "Inspirez le",
    "footer.moment": "Moment",
    "footer.description": "Chaque bouffée raconte une histoire. Laissez la fumée emporter vos pensées tandis que le coucher de soleil peint le ciel de nuances dorées.",
    "footer.tagline": "Expérience Chicha Premium",
    "auth.login": "Connexion",
    "auth.profile": "Profil",
    "auth.level": "Niv.",
    "auth.admin": "Admin",
    "auth.backToHome": "Retour à l'accueil",
    "auth.loginTitle": "Connexion",
    "auth.signupTitle": "Inscription",
    "auth.loginSubtitle": "Connectez-vous à votre compte",
    "auth.signupSubtitle": "Créez un nouveau compte",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.loginButton": "Se connecter",
    "auth.signupButton": "S'inscrire",
    "auth.noAccount": "Pas de compte ?",
    "auth.haveAccount": "Déjà un compte ?",
    "auth.terms": "En cliquant sur le bouton, vous acceptez les conditions d'utilisation",
    "auth.invalidEmail": "Format d'email invalide",
    "auth.passwordMinLength": "Le mot de passe doit contenir au moins 6 caractères",
    "auth.loginError": "Erreur de connexion",
    "auth.invalidCredentials": "Email ou mot de passe incorrect",
    "auth.error": "Erreur",
    "auth.welcome": "Bienvenue !",
    "auth.loginSuccess": "Vous êtes connecté avec succès",
    "auth.signupError": "Erreur d'inscription",
    "auth.userExists": "Un utilisateur avec cet email existe déjà",
    "auth.signupSuccess": "Inscription réussie !",
    "auth.checkEmail": "Vérifiez votre email pour confirmer votre compte",
    "auth.somethingWrong": "Une erreur s'est produite. Veuillez réessayer plus tard.",
    
    // Admin/Dashboard
    "admin.panel": "Panneau Admin",
    "admin.accounting": "Comptabilité",
    "admin.backToHome": "Retour à l'accueil",
    "admin.logout": "Déconnexion",
    "admin.overview": "Aperçu",
    "admin.orders": "Commandes",
    "admin.users": "Utilisateurs",
    "admin.totalOrders": "Total des commandes",
    "admin.pending": "En attente",
    "admin.paid": "Payé",
    "admin.today": "Aujourd'hui",
    "admin.totalRevenue": "Revenu total",
    "admin.todayRevenue": "Revenu du jour",
    "admin.totalHookahs": "Total Chichas",
    "admin.totalUsers": "Utilisateurs",
    "admin.currentOrders": "Commandes en cours",
    "admin.recentOrders": "Commandes récentes",
    "admin.allOrders": "Toutes les commandes",
    "admin.noOrders": "Aucune commande",
    "admin.hookahs": "chicha(s)",
    "admin.room": "Chambre",
    "admin.guest": "Invité",
    "admin.markAsPaid": "Marquer payé",
    "admin.cancel": "Annuler",
    "admin.statusUpdated": "Statut mis à jour",
    "admin.orderPaid": "Commande marquée payée",
    "admin.orderCancelled": "Commande annulée",
    "admin.confirmAction": "Confirmer l'action",
    "admin.confirmPaidMessage": "Êtes-vous sûr de vouloir marquer cette commande comme payée ?",
    "admin.confirmCancelMessage": "Êtes-vous sûr de vouloir annuler cette commande ?",
    "admin.confirm": "Confirmer",
    "admin.accessDenied": "Accès refusé",
    "admin.noPermission": "Vous n'avez pas la permission d'accéder à cette page",
    "admin.filterAll": "Tous",
    "admin.filterPending": "En attente",
    "admin.filterPaid": "Payés",
    "admin.filterCancelled": "Annulés",
    "admin.sortNewest": "Plus récent",
    "admin.sortOldest": "Plus ancien",
    "admin.search": "Rechercher par email, nom ou chambre...",
    "admin.total": "total",
    "admin.exportCsv": "Exporter CSV",
    "admin.revenue": "Revenu",
  },
  hi: {
    "hero.title": "हुक्का",
    "hero.subtitle": "मेन्यू",
    "hero.tagline": "धुएं की कला का अनुभव करें",
    "menu.ourSelection": "हमारा चयन",
    "menu.curatedFlavors": "चुने हुए स्वाद",
    "menu.singleFlavor": "सिंगल फ्लेवर",
    "menu.signatureMixes": "सिग्नेचर मिक्स",
    "menu.signature": "सिग्नेचर",
    "menu.extras": "अतिरिक्त",
    "menu.extrasSubtitle": "पेय और स्नैक्स",
    "menu.drinks": "पेय पदार्थ",
    "menu.snacks": "स्नैक्स",
    "menu.addons": "ऐड-ऑन",
    "strength.ultraLight": "अल्ट्रा लाइट",
    "strength.light": "लाइट",
    "strength.medium": "मध्यम",
    "strength.boldStrong": "स्ट्रॉन्ग",
    "footer.inhale": "इस पल को",
    "footer.moment": "महसूस करें",
    "footer.description": "हर कश एक कहानी कहता है। धुएं को अपने विचारों को ले जाने दें जब सूर्यास्त आकाश को सुनहरे रंगों में रंग देता है।",
    "footer.tagline": "प्रीमियम हुक्का अनुभव",
    "auth.login": "लॉगिन",
    "auth.profile": "प्रोफ़ाइल",
    "auth.level": "स्तर",
    "auth.admin": "एडमिन",
    "auth.backToHome": "होम पर वापस जाएं",
    "auth.loginTitle": "लॉगिन",
    "auth.signupTitle": "साइन अप",
    "auth.loginSubtitle": "अपने खाते में लॉगिन करें",
    "auth.signupSubtitle": "नया खाता बनाएं",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.loginButton": "लॉगिन करें",
    "auth.signupButton": "साइन अप करें",
    "auth.noAccount": "खाता नहीं है?",
    "auth.haveAccount": "पहले से खाता है?",
    "auth.terms": "बटन पर क्लिक करके, आप उपयोग की शर्तों से सहमत होते हैं",
    "auth.invalidEmail": "अमान्य ईमेल प्रारूप",
    "auth.passwordMinLength": "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
    "auth.loginError": "लॉगिन त्रुटि",
    "auth.invalidCredentials": "गलत ईमेल या पासवर्ड",
    "auth.error": "त्रुटि",
    "auth.welcome": "स्वागत है!",
    "auth.loginSuccess": "आपने सफलतापूर्वक लॉगिन किया",
    "auth.signupError": "पंजीकरण त्रुटि",
    "auth.userExists": "इस ईमेल वाला उपयोगकर्ता पहले से मौजूद है",
    "auth.signupSuccess": "पंजीकरण सफल!",
    "auth.checkEmail": "अपने खाते की पुष्टि के लिए अपना ईमेल जांचें",
    "auth.somethingWrong": "कुछ गलत हो गया। कृपया बाद में पुनः प्रयास करें।",
    
    // Admin/Dashboard
    "admin.panel": "एडमिन पैनल",
    "admin.accounting": "लेखांकन",
    "admin.backToHome": "होम पर वापस",
    "admin.logout": "लॉगआउट",
    "admin.overview": "अवलोकन",
    "admin.orders": "ऑर्डर",
    "admin.users": "उपयोगकर्ता",
    "admin.totalOrders": "कुल ऑर्डर",
    "admin.pending": "लंबित",
    "admin.paid": "भुगतान किया",
    "admin.today": "आज",
    "admin.totalRevenue": "कुल राजस्व",
    "admin.todayRevenue": "आज का राजस्व",
    "admin.totalHookahs": "कुल हुक्के",
    "admin.totalUsers": "कुल उपयोगकर्ता",
    "admin.currentOrders": "वर्तमान ऑर्डर",
    "admin.recentOrders": "हाल के ऑर्डर",
    "admin.allOrders": "सभी ऑर्डर",
    "admin.noOrders": "कोई ऑर्डर नहीं",
    "admin.hookahs": "हुक्का",
    "admin.room": "कमरा",
    "admin.guest": "अतिथि",
    "admin.markAsPaid": "भुगतान किया",
    "admin.cancel": "रद्द करें",
    "admin.statusUpdated": "स्थिति अपडेट की गई",
    "admin.orderPaid": "ऑर्डर भुगतान के रूप में चिह्नित",
    "admin.orderCancelled": "ऑर्डर रद्द किया गया",
    "admin.confirmAction": "क्रिया की पुष्टि करें",
    "admin.confirmPaidMessage": "क्या आप सुनिश्चित हैं कि इस ऑर्डर को भुगतान के रूप में चिह्नित करना चाहते हैं?",
    "admin.confirmCancelMessage": "क्या आप सुनिश्चित हैं कि इस ऑर्डर को रद्द करना चाहते हैं?",
    "admin.confirm": "पुष्टि करें",
    "admin.accessDenied": "पहुंच अस्वीकृत",
    "admin.noPermission": "आपके पास इस पेज तक पहुंचने की अनुमति नहीं है",
    "admin.search": "ईमेल, नाम या कमरे से खोजें...",
    "admin.total": "कुल",
    "admin.exportCsv": "CSV निर्यात करें",
    "admin.revenue": "राजस्व",
  },
  zh: {
    "hero.title": "水烟",
    "hero.subtitle": "菜单",
    "hero.tagline": "体验烟雾艺术",
    "menu.ourSelection": "我们的精选",
    "menu.curatedFlavors": "精选口味",
    "menu.singleFlavor": "单一口味",
    "menu.signatureMixes": "招牌混合",
    "menu.signature": "招牌",
    "menu.extras": "额外项目",
    "menu.extrasSubtitle": "饮料和小吃",
    "menu.drinks": "饮料",
    "menu.snacks": "小吃",
    "menu.addons": "附加项",
    "strength.ultraLight": "超轻",
    "strength.light": "轻度",
    "strength.medium": "中度",
    "strength.boldStrong": "浓烈",
    "footer.inhale": "感受这",
    "footer.moment": "一刻",
    "footer.description": "每一口都讲述一个故事。让烟雾带走你的思绪，当夕阳将天空染成金色。",
    "footer.tagline": "高端水烟体验",
    "auth.login": "登录",
    "auth.profile": "个人资料",
    "auth.level": "等级",
    "auth.admin": "管理",
    "auth.backToHome": "返回首页",
    "auth.loginTitle": "登录",
    "auth.signupTitle": "注册",
    "auth.loginSubtitle": "登录您的账户",
    "auth.signupSubtitle": "创建新账户",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.loginButton": "登录",
    "auth.signupButton": "注册",
    "auth.noAccount": "没有账户？",
    "auth.haveAccount": "已有账户？",
    "auth.terms": "点击按钮即表示您同意使用条款",
    "auth.invalidEmail": "邮箱格式无效",
    "auth.passwordMinLength": "密码至少需要6个字符",
    "auth.loginError": "登录错误",
    "auth.invalidCredentials": "邮箱或密码错误",
    "auth.error": "错误",
    "auth.welcome": "欢迎！",
    "auth.loginSuccess": "您已成功登录",
    "auth.signupError": "注册错误",
    "auth.userExists": "该邮箱的用户已存在",
    "auth.signupSuccess": "注册成功！",
    "auth.checkEmail": "请检查您的邮箱以确认账户",
    "auth.somethingWrong": "出现问题，请稍后重试。",
    
    // Admin/Dashboard
    "admin.panel": "管理面板",
    "admin.accounting": "财务",
    "admin.backToHome": "返回首页",
    "admin.logout": "退出登录",
    "admin.overview": "概览",
    "admin.orders": "订单",
    "admin.users": "用户",
    "admin.totalOrders": "总订单数",
    "admin.pending": "待处理",
    "admin.paid": "已支付",
    "admin.today": "今日",
    "admin.totalRevenue": "总收入",
    "admin.todayRevenue": "今日收入",
    "admin.totalHookahs": "总水烟数",
    "admin.totalUsers": "用户数",
    "admin.currentOrders": "当前订单",
    "admin.recentOrders": "最近订单",
    "admin.allOrders": "所有订单",
    "admin.noOrders": "没有订单",
    "admin.hookahs": "水烟",
    "admin.room": "房间",
    "admin.guest": "客人",
    "admin.markAsPaid": "标记已付",
    "admin.cancel": "取消",
    "admin.statusUpdated": "状态已更新",
    "admin.orderPaid": "订单已标记为已付",
    "admin.orderCancelled": "订单已取消",
    "admin.confirmAction": "确认操作",
    "admin.confirmPaidMessage": "您确定要将此订单标记为已付款吗？",
    "admin.confirmCancelMessage": "您确定要取消此订单吗？",
    "admin.confirm": "确认",
    "admin.accessDenied": "拒绝访问",
    "admin.noPermission": "您没有权限访问此页面",
    "admin.search": "按邮箱、姓名或房间搜索...",
    "admin.total": "总计",
    "admin.exportCsv": "导出CSV",
    "admin.revenue": "收入",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
