import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ru" | "id" | "uk" | "fr" | "hi" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Hero
    "hero.title": "SHISHA",
    "hero.subtitle": "MENU",
    "hero.tagline": "Experience the Art of Smoke",
    
    // Menu
    "menu.ourSelection": "Our Selection",
    "menu.curatedFlavors": "Curated Flavors",
    "menu.singleFlavor": "Single Flavor",
    "menu.signatureMixes": "Signature Mixes",
    "menu.signature": "Signature",
    "menu.addedToCart": "Added to cart!",
    "menu.loginToOrder": "Please login to order",
    "menu.clickToAdd": "Click + to add items to your order",
    "menu.loginToOrderHint": "Login to start ordering",
    "menu.extras": "Extras",
    "menu.extrasSubtitle": "Drinks & Snacks",
    "menu.drinks": "Beverages",
    "menu.snacks": "Snacks",
    "menu.addons": "Add-ons",
    
    // Cart
    "cart.title": "Your Order",
    "cart.empty": "Your cart is empty",
    "cart.total": "Total",
    "cart.placeOrder": "Place Order",
    "cart.clear": "Clear cart",
    "cart.loginRequired": "Please login to place an order",
    "cart.emptyCart": "Your cart is empty",
    "cart.orderSuccess": "Order placed successfully!",
    "cart.orderError": "Failed to place order",
    "cart.loginToOrder": "Please login to place an order",
    "cart.login": "Login",
    "cart.payNow": "Pay Now",
    "cart.payLater": "Pay Later",
    "cart.paymentError": "Payment failed. Please try again.",
    "cart.submit": "Send Order",
    
    // Navigation
    "nav.home": "Home",
    "nav.reservation": "Reservation",
    "nav.feedback": "Feedback",
    "nav.history": "History",
    "nav.profile": "Profile",
    
    // Reservation
    "reservation.title": "Party Reservation",
    "reservation.subtitle": "Book your shisha experience",
    "reservation.selectDateTime": "Select Date & Time",
    "reservation.date": "Reservation Date",
    "reservation.selectDate": "Select a date",
    "reservation.time": "Reservation Time",
    "reservation.selectTime": "Select reservation time",
    "reservation.partySize": "Party Size",
    "reservation.hookahCount": "Hookah Count",
    "reservation.hookahCountDesc": "How many hookahs do you need for your party?",
    "reservation.additionalInfo": "Additional Information",
    "reservation.phone": "Phone Number",
    "reservation.notes": "Notes",
    "reservation.notesPlaceholder": "Any special notes for your reservation",
    "reservation.specialRequests": "Special Requests",
    "reservation.specialRequestsPlaceholder": "Preferred flavors, seating preferences, etc.",
    "reservation.submit": "Book Reservation",
    "reservation.submitting": "Booking...",
    "reservation.fillRequired": "Please fill in all required fields",
    "reservation.success": "Reservation submitted successfully!",
    "reservation.error": "Failed to submit reservation",
    
    // Order History
    "history.title": "Order History",
    "history.subtitle": "Your past orders",
    "history.noOrders": "No orders yet",
    "history.hookahs": "hookah(s)",
    "history.paid": "Paid",
    "history.pending": "Pending",
    "history.delivered": "Delivered",
    "history.cancelled": "Cancelled",
    
    // Feedback
    "feedback.title": "Your Feedback",
    "feedback.subtitle": "Help us improve your experience",
    "feedback.rateExperience": "Rate Your Experience",
    "feedback.tellUsMore": "Tell us more",
    "feedback.placeholder": "Share your thoughts, suggestions, or comments...",
    "feedback.submit": "Submit Feedback",
    "feedback.submitting": "Submitting...",
    "feedback.ratingRequired": "Please select a rating",
    "feedback.success": "Thank you for your feedback!",
    
    // Order Confirmation
    "order.confirmed": "Order Confirmed!",
    "order.thankYou": "Thank you for your order",
    "order.orderNumber": "Order Number",
    "order.estimatedTime": "Estimated Wait Time",
    "order.approx": "Approx.",
    "order.minutes": "minutes",
    "order.summary": "Order Summary",
    "order.backToMenu": "Back to Menu",
    "order.viewProfile": "View Profile",
    "order.notification": "We'll notify you when your order is ready",
    "order.deliveryTo": "Delivery to room",
    "order.wrongRoom": "If the room number is incorrect, please update it",
    "order.updateRoom": "Update room number",
    "order.noRoom": "Room number not specified",
    "order.addRoomHint": "Add your room number for delivery",
    "order.addRoom": "Add room number",
    "order.cancelOrder": "Cancel Order",
    "order.cancelling": "Cancelling...",
    "order.cancelled": "Order Cancelled",
    "order.cancelledDesc": "Your order has been cancelled",
    "order.cancelError": "Cancel Error",
    "order.cancelErrorDesc": "Failed to cancel order. Please try again.",
    "order.ready": "Order Ready!",
    "order.readyDesc": "Your order is ready for pickup/delivery",
    
    // Strength levels
    "strength.ultraLight": "Ultra Light",
    "strength.light": "Light",
    "strength.medium": "Medium",
    "strength.boldStrong": "Bold Strong",
    
    // Footer
    "footer.inhale": "Inhale the",
    "footer.moment": "Moment",
    "footer.description": "Each puff tells a story. Let the smoke carry your thoughts as the sunset paints the sky in shades of gold.",
    "footer.tagline": "Premium Shisha Experience",
    
    // Auth
    "auth.login": "Login",
    "auth.profile": "Profile",
    "auth.level": "Lvl.",
    "auth.admin": "Admin",
    "auth.accounting": "Accounting",
    "auth.shishaMaster": "Shisha Master",
    "auth.backToHome": "Back to Home",
    "auth.loginTitle": "Login",
    "auth.signupTitle": "Sign Up",
    "auth.loginSubtitle": "Log in to your account",
    "auth.signupSubtitle": "Create a new account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.loginButton": "Log In",
    "auth.signupButton": "Sign Up",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    "auth.terms": "By clicking the button, you agree to the terms of use",
    "auth.invalidEmail": "Invalid email format",
    "auth.passwordMinLength": "Password must be at least 6 characters",
    "auth.loginError": "Login Error",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.error": "Error",
    "auth.welcome": "Welcome!",
    "auth.loginSuccess": "You have successfully logged in",
    "auth.signupError": "Registration Error",
    "auth.userExists": "A user with this email already exists",
    "auth.signupSuccess": "Registration successful!",
    "auth.checkEmail": "Check your email to confirm your account",
    "auth.somethingWrong": "Something went wrong. Please try again later.",
    
    // Admin/Dashboard
    "admin.panel": "Admin Panel",
    "admin.accounting": "Accounting",
    "admin.backToHome": "Back to Home",
    "admin.logout": "Logout",
    "admin.overview": "Overview",
    "admin.orders": "Orders",
    "admin.users": "Users",
    "admin.totalOrders": "Total Orders",
    "admin.pending": "Pending",
    "admin.paid": "Paid",
    "admin.today": "Today",
    "admin.totalRevenue": "Total Revenue",
    "admin.todayRevenue": "Today's Revenue",
    "admin.totalHookahs": "Total Hookahs",
    "admin.totalUsers": "Total Users",
    "admin.currentOrders": "Current Orders",
    "admin.recentOrders": "Recent Orders",
    "admin.allOrders": "All Orders",
    "admin.noOrders": "No orders",
    "admin.hookahs": "hookah(s)",
    "admin.room": "Room",
    "admin.guest": "Guest",
    "admin.markAsPaid": "Mark as Paid",
    "admin.cancel": "Cancel",
    "admin.statusUpdated": "Status Updated",
    "admin.orderPaid": "Order marked as paid",
    "admin.orderCancelled": "Order cancelled",
    "admin.confirmAction": "Confirm Action",
    "admin.confirmPaidMessage": "Are you sure you want to mark this order as paid?",
    "admin.confirmCancelMessage": "Are you sure you want to cancel this order?",
    "admin.confirm": "Confirm",
    "admin.accessDenied": "Access Denied",
    "admin.noPermission": "You don't have permission to access this page",
    "admin.filterAll": "All",
    "admin.filterPending": "Pending",
    "admin.filterPaid": "Paid",
    "admin.filterCancelled": "Cancelled",
    "admin.sortNewest": "Newest",
    "admin.sortOldest": "Oldest",
    "admin.addPurchase": "Add Purchase",
    "admin.hookahCount": "Hookah Count",
    "admin.amount": "Amount",
    "admin.notes": "Notes",
    "admin.optional": "Optional",
    "admin.freeDrink": "Free Drink",
    "admin.freeSnack": "Free Snack",
    "admin.save": "Save",
    "admin.purchaseAdded": "Purchase Added",
    "admin.selectUser": "Select a user",
    "admin.orderHistory": "Order History",
    "admin.noName": "No name",
    "admin.drink": "Drink",
    "admin.snack": "Snack",
    "admin.manageRoles": "Manage Roles",
    "admin.roleAdded": "Role Added",
    "admin.roleRemoved": "Role Removed",
    "admin.search": "Search by email, name or room...",
    "admin.total": "total",
    "admin.exportCsv": "Export CSV",
    "admin.dateRange": "Date Range",
    "admin.revenue": "Revenue",
    "admin.settings": "Settings",
    "admin.deliveryTime": "Delivery Time",
    "admin.deliveryTimeDesc": "Maximum time for order delivery to customer",
    "admin.minutes": "minutes",
    "admin.saving": "Saving...",
    "admin.settingsSaved": "Settings saved",
    "admin.settingsError": "Error saving settings",
    
    // Roles
    "role.admin": "Admin",
    "role.guest": "Guest",
    "role.shishaMaster": "Shisha Master",
    "role.accounting": "Accounting",
    
    // Shisha Master
    "shishaMaster.title": "Shisha Master",
    "shishaMaster.tabs.videos": "Video Instructions",
    "shishaMaster.tabs.documents": "Documents",
    "shishaMaster.duration": "Duration",
    "shishaMaster.documentsTitle": "Instructions & Rules",
    "shishaMaster.download": "Download",
    "shishaMaster.video.basics": "Hookah Preparation Basics",
    "shishaMaster.video.coals": "Working with Coals",
    "shishaMaster.video.flavors": "Mixing Flavors Guide",
    "shishaMaster.video.cleaning": "Cleaning & Maintenance",
    "shishaMaster.doc.safetyRules": "Safety Rules",
    "shishaMaster.doc.serviceStandards": "Service Standards",
    "shishaMaster.doc.tobaccoGuide": "Tobacco Handling Guide",
    "shishaMaster.doc.equipmentManual": "Equipment Manual",
    "shishaMaster.doc.hygieneProtocol": "Hygiene Protocol",
    "shishaMaster.orders.activeOrders": "Active Orders",
    "shishaMaster.orders.orders": "orders",
    "shishaMaster.orders.noOrders": "No active orders",
    "shishaMaster.orders.timeRemaining": "Time remaining",
    "shishaMaster.orders.overdue": "OVERDUE",
    "shishaMaster.orders.markDelivered": "Mark Delivered",
    "shishaMaster.orders.cancelOrder": "Cancel Order",
    "shishaMaster.orders.delivered": "Order marked as delivered",
    "shishaMaster.orders.cancelled": "Order cancelled",
    "shishaMaster.orders.error": "Error updating order",
    "shishaMaster.orders.cancelOrderTitle": "Cancel Order",
    "shishaMaster.orders.cancelOrderDesc": "Please provide a reason for cancelling this order.",
    "shishaMaster.orders.cancelReasonPlaceholder": "Enter cancellation reason...",
    "shishaMaster.orders.cancelReason": "Cancellation reason",
    "shishaMaster.orders.confirmCancel": "Confirm Cancel",
    "shishaMaster.orders.history": "History",
    "shishaMaster.orders.noHistory": "No completed orders yet",
    "shishaMaster.orders.statusDelivered": "Delivered",
    "shishaMaster.orders.statusCancelled": "Cancelled",
    
    // Payment
    "payment.methods": "Payment Methods",
    "payment.bankTransfer": "Bank Transfer (IDR)",
    "payment.cash": "Cash at Reception",
    "payment.cashDescription": "Pay in cash at the reception desk",
    "payment.accountName": "Account Name",
    "payment.bankName": "Bank",
    "payment.accountNumber": "Account Number",
    "payment.copy": "Copy",
  },
  ru: {
    "hero.title": "КАЛЬЯН",
    "hero.subtitle": "МЕНЮ",
    "hero.tagline": "Искусство дыма",
    "menu.ourSelection": "Наш выбор",
    "menu.curatedFlavors": "Избранные вкусы",
    "menu.singleFlavor": "Одиночный вкус",
    "menu.signatureMixes": "Фирменные миксы",
    "menu.signature": "Фирменный",
    "menu.addedToCart": "Добавлено в корзину!",
    "menu.loginToOrder": "Войдите, чтобы сделать заказ",
    "menu.clickToAdd": "Нажмите + чтобы добавить в заказ",
    "menu.loginToOrderHint": "Войдите, чтобы начать заказ",
    "menu.extras": "Дополнительно",
    "menu.extrasSubtitle": "Напитки и закуски",
    "menu.drinks": "Напитки",
    "menu.snacks": "Закуски",
    "menu.addons": "Дополнения",
    "cart.title": "Ваш заказ",
    "cart.empty": "Корзина пуста",
    "cart.total": "Итого",
    "cart.placeOrder": "Оформить заказ",
    "cart.clear": "Очистить корзину",
    "cart.loginRequired": "Войдите, чтобы оформить заказ",
    "cart.emptyCart": "Корзина пуста",
    "cart.orderSuccess": "Заказ успешно оформлен!",
    "cart.orderError": "Ошибка оформления заказа",
    "cart.loginToOrder": "Войдите, чтобы оформить заказ",
    "cart.login": "Войти",
    "cart.payNow": "Оплатить сейчас",
    "cart.payLater": "Оплатить позже",
    "cart.paymentError": "Ошибка оплаты. Попробуйте ещё раз.",
    "cart.submit": "Отправить заказ",
    
    // Navigation
    "nav.home": "Главная",
    "nav.reservation": "Бронь",
    "nav.feedback": "Отзывы",
    "nav.history": "История",
    "nav.profile": "Профиль",
    
    // Reservation
    "reservation.title": "Бронирование",
    "reservation.subtitle": "Забронируйте ваш кальянный опыт",
    "reservation.selectDateTime": "Выберите дату и время",
    "reservation.date": "Дата бронирования",
    "reservation.selectDate": "Выберите дату",
    "reservation.time": "Время бронирования",
    "reservation.selectTime": "Выберите время",
    "reservation.partySize": "Количество гостей",
    "reservation.hookahCount": "Количество кальянов",
    "reservation.hookahCountDesc": "Сколько кальянов вам нужно для вечеринки?",
    "reservation.additionalInfo": "Дополнительная информация",
    "reservation.phone": "Номер телефона",
    "reservation.notes": "Примечания",
    "reservation.notesPlaceholder": "Особые пожелания к бронированию",
    "reservation.specialRequests": "Особые запросы",
    "reservation.specialRequestsPlaceholder": "Предпочтительные вкусы, места и т.д.",
    "reservation.submit": "Забронировать",
    "reservation.submitting": "Бронирование...",
    "reservation.fillRequired": "Заполните все обязательные поля",
    "reservation.success": "Бронирование успешно отправлено!",
    "reservation.error": "Ошибка отправки бронирования",
    
    // Order History
    "history.title": "История заказов",
    "history.subtitle": "Ваши прошлые заказы",
    "history.noOrders": "Заказов пока нет",
    "history.hookahs": "кальян(ов)",
    "history.paid": "Оплачено",
    "history.pending": "Ожидает",
    "history.delivered": "Доставлено",
    "history.cancelled": "Отменено",
    
    // Feedback
    "feedback.title": "Ваш отзыв",
    "feedback.subtitle": "Помогите нам улучшить сервис",
    "feedback.rateExperience": "Оцените ваш опыт",
    "feedback.tellUsMore": "Расскажите подробнее",
    "feedback.placeholder": "Поделитесь мыслями, предложениями или комментариями...",
    "feedback.submit": "Отправить отзыв",
    "feedback.submitting": "Отправка...",
    "feedback.ratingRequired": "Выберите оценку",
    "feedback.success": "Спасибо за ваш отзыв!",
    
    "order.confirmed": "Заказ подтверждён!",
    "order.thankYou": "Спасибо за ваш заказ",
    "order.orderNumber": "Номер заказа",
    "order.estimatedTime": "Ожидаемое время",
    "order.approx": "Примерно",
    "order.minutes": "минут",
    "order.summary": "Состав заказа",
    "order.backToMenu": "Вернуться к меню",
    "order.viewProfile": "Мой профиль",
    "order.notification": "Мы уведомим вас, когда заказ будет готов",
    "order.deliveryTo": "Доставка в комнату",
    "order.wrongRoom": "Если номер комнаты неверный, пожалуйста, обновите его",
    "order.updateRoom": "Изменить номер комнаты",
    "order.noRoom": "Номер комнаты не указан",
    "order.addRoomHint": "Добавьте номер комнаты для доставки",
    "order.addRoom": "Указать номер комнаты",
    "order.cancelOrder": "Отменить заказ",
    "order.cancelling": "Отмена...",
    "order.cancelled": "Заказ отменён",
    "order.cancelledDesc": "Ваш заказ был отменён",
    "order.cancelError": "Ошибка отмены",
    "order.cancelErrorDesc": "Не удалось отменить заказ. Попробуйте ещё раз.",
    "order.ready": "Заказ готов!",
    "order.readyDesc": "Ваш заказ готов к выдаче/доставке",
    "strength.ultraLight": "Ультра лёгкий",
    "strength.light": "Лёгкий",
    "strength.medium": "Средний",
    "strength.boldStrong": "Крепкий",
    "footer.inhale": "Вдохни",
    "footer.moment": "Момент",
    "footer.description": "Каждая затяжка рассказывает историю. Пусть дым унесёт твои мысли, пока закат окрашивает небо в золотые оттенки.",
    "footer.tagline": "Премиум кальянный опыт",
    "auth.login": "Войти",
    "auth.profile": "Профиль",
    "auth.level": "Ур.",
    "auth.admin": "Админ",
    "auth.accounting": "Бухгалтерия",
    "auth.shishaMaster": "Кальянщик",
    "auth.backToHome": "На главную",
    "auth.loginTitle": "Вход",
    "auth.signupTitle": "Регистрация",
    "auth.loginSubtitle": "Войдите в свой аккаунт",
    "auth.signupSubtitle": "Создайте новый аккаунт",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.loginButton": "Войти",
    "auth.signupButton": "Зарегистрироваться",
    "auth.noAccount": "Нет аккаунта?",
    "auth.haveAccount": "Уже есть аккаунт?",
    "auth.terms": "Нажимая кнопку, вы соглашаетесь с условиями использования",
    "auth.invalidEmail": "Неверный формат email",
    "auth.passwordMinLength": "Пароль должен содержать минимум 6 символов",
    "auth.loginError": "Ошибка входа",
    "auth.invalidCredentials": "Неверный email или пароль",
    "auth.error": "Ошибка",
    "auth.welcome": "Добро пожаловать!",
    "auth.loginSuccess": "Вы успешно вошли в систему",
    "auth.signupError": "Ошибка регистрации",
    "auth.userExists": "Пользователь с таким email уже существует",
    "auth.signupSuccess": "Регистрация успешна!",
    "auth.checkEmail": "Проверьте вашу почту для подтверждения аккаунта",
    "auth.somethingWrong": "Что-то пошло не так. Попробуйте позже.",
    
    // Admin/Dashboard
    "admin.panel": "Админ панель",
    "admin.accounting": "Бухгалтерия",
    "admin.backToHome": "На главную",
    "admin.logout": "Выйти",
    "admin.overview": "Обзор",
    "admin.orders": "Заказы",
    "admin.users": "Пользователи",
    "admin.totalOrders": "Всего заказов",
    "admin.pending": "Ожидают оплаты",
    "admin.paid": "Оплачено",
    "admin.today": "Сегодня",
    "admin.totalRevenue": "Общая выручка",
    "admin.todayRevenue": "Выручка сегодня",
    "admin.totalHookahs": "Всего кальянов",
    "admin.totalUsers": "Пользователей",
    "admin.currentOrders": "Текущие заказы",
    "admin.recentOrders": "Последние заказы",
    "admin.allOrders": "Все заказы",
    "admin.noOrders": "Нет заказов",
    "admin.hookahs": "кальян(ов)",
    "admin.room": "Комната",
    "admin.guest": "Гость",
    "admin.markAsPaid": "Оплачено",
    "admin.cancel": "Отмена",
    "admin.statusUpdated": "Статус обновлён",
    "admin.orderPaid": "Заказ отмечен как оплаченный",
    "admin.orderCancelled": "Заказ отменён",
    "admin.confirmAction": "Подтвердите действие",
    "admin.confirmPaidMessage": "Вы уверены, что хотите отметить этот заказ как оплаченный?",
    "admin.confirmCancelMessage": "Вы уверены, что хотите отменить этот заказ?",
    "admin.confirm": "Подтвердить",
    "admin.accessDenied": "Доступ запрещён",
    "admin.noPermission": "У вас нет прав для доступа к этой странице",
    "admin.filterAll": "Все",
    "admin.filterPending": "Ожидают",
    "admin.filterPaid": "Оплачены",
    "admin.filterCancelled": "Отменены",
    "admin.sortNewest": "Новые",
    "admin.sortOldest": "Старые",
    "admin.addPurchase": "Добавить покупку",
    "admin.hookahCount": "Количество кальянов",
    "admin.amount": "Сумма",
    "admin.notes": "Заметка",
    "admin.optional": "Необязательно",
    "admin.freeDrink": "Бесплатный напиток",
    "admin.freeSnack": "Бесплатный снек",
    "admin.save": "Сохранить",
    "admin.purchaseAdded": "Покупка добавлена",
    "admin.selectUser": "Выберите пользователя",
    "admin.orderHistory": "История заказов",
    "admin.noName": "Без имени",
    "admin.drink": "Напиток",
    "admin.snack": "Снек",
    "admin.manageRoles": "Управление ролями",
    "admin.roleAdded": "Роль добавлена",
    "admin.roleRemoved": "Роль удалена",
    "admin.search": "Поиск по email, имени или комнате...",
    "admin.total": "всего",
    "admin.exportCsv": "Экспорт CSV",
    "admin.dateRange": "Период",
    "admin.revenue": "Выручка",
    "admin.settings": "Настройки",
    "admin.deliveryTime": "Время доставки",
    "admin.deliveryTimeDesc": "Максимальное время для доставки заказа клиенту",
    "admin.minutes": "минут",
    "admin.saving": "Сохранение...",
    "admin.settingsSaved": "Настройки сохранены",
    "admin.settingsError": "Ошибка сохранения настроек",
    
    // Roles
    "role.admin": "Админ",
    "role.guest": "Гость",
    "role.shishaMaster": "Shisha Master",
    "role.accounting": "Бухгалтерия",
    
    // Shisha Master
    "shishaMaster.title": "Shisha Master",
    "shishaMaster.tabs.videos": "Видео инструкции",
    "shishaMaster.tabs.documents": "Документы",
    "shishaMaster.duration": "Длительность",
    "shishaMaster.documentsTitle": "Инструкции и правила",
    "shishaMaster.download": "Скачать",
    "shishaMaster.video.basics": "Основы приготовления кальяна",
    "shishaMaster.video.coals": "Работа с углями",
    "shishaMaster.video.flavors": "Смешивание вкусов",
    "shishaMaster.video.cleaning": "Чистка и обслуживание",
    "shishaMaster.doc.safetyRules": "Правила безопасности",
    "shishaMaster.doc.serviceStandards": "Стандарты обслуживания",
    "shishaMaster.doc.tobaccoGuide": "Руководство по табаку",
    "shishaMaster.doc.equipmentManual": "Руководство по оборудованию",
    "shishaMaster.doc.hygieneProtocol": "Протокол гигиены",
    "shishaMaster.orders.activeOrders": "Активные заказы",
    "shishaMaster.orders.orders": "заказов",
    "shishaMaster.orders.noOrders": "Нет активных заказов",
    "shishaMaster.orders.timeRemaining": "Осталось времени",
    "shishaMaster.orders.overdue": "ПРОСРОЧЕНО",
    "shishaMaster.orders.markDelivered": "Доставлено",
    "shishaMaster.orders.cancelOrder": "Отменить",
    "shishaMaster.orders.delivered": "Заказ отмечен как доставленный",
    "shishaMaster.orders.cancelled": "Заказ отменён",
    "shishaMaster.orders.error": "Ошибка обновления заказа",
    "shishaMaster.orders.cancelOrderTitle": "Отменить заказ",
    "shishaMaster.orders.cancelOrderDesc": "Укажите причину отмены заказа.",
    "shishaMaster.orders.cancelReasonPlaceholder": "Введите причину отмены...",
    "shishaMaster.orders.cancelReason": "Причина отмены",
    "shishaMaster.orders.confirmCancel": "Подтвердить отмену",
    "shishaMaster.orders.history": "История",
    "shishaMaster.orders.noHistory": "Нет завершённых заказов",
    "shishaMaster.orders.statusDelivered": "Доставлено",
    "shishaMaster.orders.statusCancelled": "Отменено",
    
    // Payment
    "payment.methods": "Способы оплаты",
    "payment.bankTransfer": "Банковский перевод (IDR)",
    "payment.cash": "Наличными на ресепшн",
    "payment.cashDescription": "Оплата наличными на ресепшн",
    "payment.accountName": "Имя счёта",
    "payment.bankName": "Банк",
    "payment.accountNumber": "Номер счёта",
    "payment.copy": "Копировать",
  },
  id: {
    "hero.title": "SHISHA",
    "hero.subtitle": "MENU",
    "cart.submit": "Kirim Pesanan",
    "nav.home": "Beranda",
    "nav.reservation": "Reservasi",
    "nav.feedback": "Ulasan",
    "nav.history": "Riwayat",
    "nav.profile": "Profil",
    "reservation.title": "Reservasi Pesta",
    "reservation.subtitle": "Pesan pengalaman shisha Anda",
    "reservation.selectDateTime": "Pilih Tanggal & Waktu",
    "reservation.date": "Tanggal Reservasi",
    "reservation.selectDate": "Pilih tanggal",
    "reservation.time": "Waktu Reservasi",
    "reservation.selectTime": "Pilih waktu reservasi",
    "reservation.partySize": "Jumlah Tamu",
    "reservation.hookahCount": "Jumlah Shisha",
    "reservation.hookahCountDesc": "Berapa shisha yang Anda butuhkan untuk pesta?",
    "reservation.additionalInfo": "Informasi Tambahan",
    "reservation.phone": "Nomor Telepon",
    "reservation.notes": "Catatan",
    "reservation.notesPlaceholder": "Catatan khusus untuk reservasi Anda",
    "reservation.specialRequests": "Permintaan Khusus",
    "reservation.specialRequestsPlaceholder": "Rasa favorit, preferensi tempat duduk, dll.",
    "reservation.submit": "Pesan Reservasi",
    "reservation.submitting": "Memesan...",
    "reservation.fillRequired": "Harap isi semua bidang yang wajib",
    "reservation.success": "Reservasi berhasil dikirim!",
    "reservation.error": "Gagal mengirim reservasi",
    "history.title": "Riwayat Pesanan",
    "history.subtitle": "Pesanan Anda sebelumnya",
    "history.noOrders": "Belum ada pesanan",
    "history.hookahs": "shisha",
    "history.paid": "Dibayar",
    "history.pending": "Menunggu",
    "history.delivered": "Terkirim",
    "history.cancelled": "Dibatalkan",
    "feedback.title": "Ulasan Anda",
    "feedback.subtitle": "Bantu kami meningkatkan pengalaman Anda",
    "feedback.rateExperience": "Nilai Pengalaman Anda",
    "feedback.tellUsMore": "Ceritakan lebih lanjut",
    "feedback.placeholder": "Bagikan pemikiran, saran, atau komentar Anda...",
    "feedback.submit": "Kirim Ulasan",
    "feedback.submitting": "Mengirim...",
    "feedback.ratingRequired": "Pilih penilaian",
    "feedback.success": "Terima kasih atas ulasan Anda!",
    "hero.tagline": "Rasakan Seni Asap",
    "menu.ourSelection": "Pilihan Kami",
    "menu.curatedFlavors": "Rasa Terpilih",
    "menu.singleFlavor": "Rasa Tunggal",
    "menu.signatureMixes": "Campuran Khas",
    "menu.signature": "Khas",
    "menu.extras": "Tambahan",
    "menu.extrasSubtitle": "Minuman & Makanan Ringan",
    "menu.drinks": "Minuman",
    "menu.snacks": "Makanan Ringan",
    "menu.addons": "Tambahan",
    "strength.ultraLight": "Ultra Ringan",
    "strength.light": "Ringan",
    "strength.medium": "Sedang",
    "strength.boldStrong": "Kuat",
    "footer.inhale": "Hirup",
    "footer.moment": "Momen",
    "footer.description": "Setiap hisapan menceritakan sebuah kisah. Biarkan asap membawa pikiranmu saat matahari terbenam melukis langit dengan warna emas.",
    "footer.tagline": "Pengalaman Shisha Premium",
    "auth.login": "Masuk",
    "auth.profile": "Profil",
    "auth.level": "Lvl.",
    "auth.admin": "Admin",
    "auth.accounting": "Akuntansi",
    "auth.shishaMaster": "Shisha Master",
    "auth.backToHome": "Kembali ke Beranda",
    "auth.loginTitle": "Masuk",
    "auth.signupTitle": "Daftar",
    "auth.loginSubtitle": "Masuk ke akun Anda",
    "auth.signupSubtitle": "Buat akun baru",
    "auth.email": "Email",
    "auth.password": "Kata Sandi",
    "auth.loginButton": "Masuk",
    "auth.signupButton": "Daftar",
    "auth.noAccount": "Belum punya akun?",
    "auth.haveAccount": "Sudah punya akun?",
    "auth.terms": "Dengan mengklik tombol, Anda menyetujui ketentuan penggunaan",
    "auth.invalidEmail": "Format email tidak valid",
    "auth.passwordMinLength": "Kata sandi minimal 6 karakter",
    "auth.loginError": "Kesalahan Masuk",
    "auth.invalidCredentials": "Email atau kata sandi salah",
    "auth.error": "Kesalahan",
    "auth.welcome": "Selamat Datang!",
    "auth.loginSuccess": "Anda berhasil masuk",
    "auth.signupError": "Kesalahan Pendaftaran",
    "auth.userExists": "Pengguna dengan email ini sudah ada",
    "auth.signupSuccess": "Pendaftaran berhasil!",
    "auth.checkEmail": "Periksa email Anda untuk mengonfirmasi akun",
    "auth.somethingWrong": "Terjadi kesalahan. Silakan coba lagi nanti.",
    
    // Admin/Dashboard
    "admin.panel": "Panel Admin",
    "admin.accounting": "Akuntansi",
    "admin.backToHome": "Kembali ke Beranda",
    "admin.logout": "Keluar",
    "admin.overview": "Ringkasan",
    "admin.orders": "Pesanan",
    "admin.users": "Pengguna",
    "admin.totalOrders": "Total Pesanan",
    "admin.pending": "Menunggu",
    "admin.paid": "Dibayar",
    "admin.today": "Hari Ini",
    "admin.totalRevenue": "Total Pendapatan",
    "admin.todayRevenue": "Pendapatan Hari Ini",
    "admin.totalHookahs": "Total Shisha",
    "admin.totalUsers": "Total Pengguna",
    "admin.currentOrders": "Pesanan Saat Ini",
    "admin.recentOrders": "Pesanan Terbaru",
    "admin.allOrders": "Semua Pesanan",
    "admin.noOrders": "Tidak ada pesanan",
    "admin.hookahs": "shisha",
    "admin.room": "Kamar",
    "admin.guest": "Tamu",
    "admin.markAsPaid": "Tandai Dibayar",
    "admin.cancel": "Batal",
    "admin.statusUpdated": "Status Diperbarui",
    "admin.orderPaid": "Pesanan ditandai dibayar",
    "admin.orderCancelled": "Pesanan dibatalkan",
    "admin.confirmAction": "Konfirmasi Tindakan",
    "admin.confirmPaidMessage": "Apakah Anda yakin ingin menandai pesanan ini sebagai dibayar?",
    "admin.confirmCancelMessage": "Apakah Anda yakin ingin membatalkan pesanan ini?",
    "admin.confirm": "Konfirmasi",
    "admin.accessDenied": "Akses Ditolak",
    "admin.noPermission": "Anda tidak memiliki izin untuk mengakses halaman ini",
    "admin.filterAll": "Semua",
    "admin.filterPending": "Menunggu",
    "admin.filterPaid": "Dibayar",
    "admin.filterCancelled": "Dibatalkan",
    "admin.sortNewest": "Terbaru",
    "admin.sortOldest": "Terlama",
    "admin.addPurchase": "Tambah Pembelian",
    "admin.hookahCount": "Jumlah Shisha",
    "admin.amount": "Jumlah",
    "admin.notes": "Catatan",
    "admin.optional": "Opsional",
    "admin.freeDrink": "Minuman Gratis",
    "admin.freeSnack": "Makanan Gratis",
    "admin.save": "Simpan",
    "admin.purchaseAdded": "Pembelian Ditambahkan",
    "admin.selectUser": "Pilih pengguna",
    "admin.orderHistory": "Riwayat Pesanan",
    "admin.noName": "Tanpa nama",
    "admin.drink": "Minuman",
    "admin.snack": "Makanan",
    "admin.manageRoles": "Kelola Peran",
    "admin.roleAdded": "Peran Ditambahkan",
    "admin.roleRemoved": "Peran Dihapus",
    "admin.search": "Cari berdasarkan email, nama atau kamar...",
    "admin.total": "total",
    "admin.exportCsv": "Ekspor CSV",
    "admin.dateRange": "Rentang Tanggal",
    "admin.revenue": "Pendapatan",
    "admin.settings": "Pengaturan",
    "admin.deliveryTime": "Waktu Pengiriman",
    "admin.deliveryTimeDesc": "Waktu maksimal untuk pengiriman pesanan ke pelanggan",
    "admin.minutes": "menit",
    "admin.saving": "Menyimpan...",
    "admin.settingsSaved": "Pengaturan disimpan",
    "admin.settingsError": "Kesalahan menyimpan pengaturan",
    
    // Roles
    "role.admin": "Admin",
    "role.guest": "Tamu",
    "role.shishaMaster": "Shisha Master",
    "role.accounting": "Akuntansi",
    
    // Shisha Master
    "shishaMaster.title": "Shisha Master",
    "shishaMaster.tabs.videos": "Video Instruksi",
    "shishaMaster.tabs.documents": "Dokumen",
    "shishaMaster.duration": "Durasi",
    "shishaMaster.documentsTitle": "Instruksi & Aturan",
    "shishaMaster.download": "Unduh",
    "shishaMaster.video.basics": "Dasar-dasar Persiapan Shisha",
    "shishaMaster.video.coals": "Bekerja dengan Arang",
    "shishaMaster.video.flavors": "Panduan Mencampur Rasa",
    "shishaMaster.video.cleaning": "Pembersihan & Perawatan",
    "shishaMaster.doc.safetyRules": "Aturan Keselamatan",
    "shishaMaster.doc.serviceStandards": "Standar Pelayanan",
    "shishaMaster.doc.tobaccoGuide": "Panduan Penanganan Tembakau",
    "shishaMaster.doc.equipmentManual": "Manual Peralatan",
    "shishaMaster.doc.hygieneProtocol": "Protokol Kebersihan",
    "shishaMaster.orders.activeOrders": "Pesanan Aktif",
    "shishaMaster.orders.orders": "pesanan",
    "shishaMaster.orders.noOrders": "Tidak ada pesanan aktif",
    "shishaMaster.orders.timeRemaining": "Waktu tersisa",
    "shishaMaster.orders.overdue": "TERLAMBAT",
    "shishaMaster.orders.markDelivered": "Tandai Terkirim",
    "shishaMaster.orders.cancelOrder": "Batalkan",
    "shishaMaster.orders.delivered": "Pesanan ditandai terkirim",
    "shishaMaster.orders.cancelled": "Pesanan dibatalkan",
    "shishaMaster.orders.error": "Kesalahan memperbarui pesanan",
    "shishaMaster.orders.cancelOrderTitle": "Batalkan Pesanan",
    "shishaMaster.orders.cancelOrderDesc": "Berikan alasan pembatalan pesanan ini.",
    "shishaMaster.orders.cancelReasonPlaceholder": "Masukkan alasan pembatalan...",
    "shishaMaster.orders.cancelReason": "Alasan pembatalan",
    "shishaMaster.orders.confirmCancel": "Konfirmasi Batal",
    "shishaMaster.orders.history": "Riwayat",
    "shishaMaster.orders.noHistory": "Belum ada pesanan selesai",
    "shishaMaster.orders.statusDelivered": "Terkirim",
    "shishaMaster.orders.statusCancelled": "Dibatalkan",
    
    // Payment
    "payment.methods": "Metode Pembayaran",
    "payment.bankTransfer": "Transfer Bank (IDR)",
    "payment.cash": "Tunai di Resepsionis",
    "payment.cashDescription": "Bayar tunai di meja resepsionis",
    "payment.accountName": "Nama Rekening",
    "payment.bankName": "Bank",
    "payment.accountNumber": "Nomor Rekening",
    "payment.copy": "Salin",
  },
  uk: {
    "hero.title": "КАЛЬЯН",
    "hero.subtitle": "МЕНЮ",
    "cart.submit": "Надіслати замовлення",
    "nav.home": "Головна",
    "nav.reservation": "Бронювання",
    "nav.feedback": "Відгуки",
    "nav.history": "Історія",
    "nav.profile": "Профіль",
    "reservation.title": "Бронювання вечірки",
    "reservation.subtitle": "Забронюйте свій кальянний досвід",
    "reservation.selectDateTime": "Виберіть дату та час",
    "reservation.date": "Дата бронювання",
    "reservation.selectDate": "Виберіть дату",
    "reservation.time": "Час бронювання",
    "reservation.selectTime": "Виберіть час бронювання",
    "reservation.partySize": "Кількість гостей",
    "reservation.hookahCount": "Кількість кальянів",
    "reservation.hookahCountDesc": "Скільки кальянів вам потрібно для вечірки?",
    "reservation.additionalInfo": "Додаткова інформація",
    "reservation.phone": "Номер телефону",
    "reservation.notes": "Примітки",
    "reservation.notesPlaceholder": "Особливі побажання до бронювання",
    "reservation.specialRequests": "Особливі запити",
    "reservation.specialRequestsPlaceholder": "Улюблені смаки, переваги місць і т.д.",
    "reservation.submit": "Забронювати",
    "reservation.submitting": "Бронювання...",
    "reservation.fillRequired": "Заповніть всі обов'язкові поля",
    "reservation.success": "Бронювання успішно надіслано!",
    "reservation.error": "Помилка надсилання бронювання",
    "history.title": "Історія замовлень",
    "history.subtitle": "Ваші минулі замовлення",
    "history.noOrders": "Замовлень поки немає",
    "history.hookahs": "кальян(ів)",
    "history.paid": "Оплачено",
    "history.pending": "Очікує",
    "history.delivered": "Доставлено",
    "history.cancelled": "Скасовано",
    "feedback.title": "Ваш відгук",
    "feedback.subtitle": "Допоможіть нам покращити сервіс",
    "feedback.rateExperience": "Оцініть ваш досвід",
    "feedback.tellUsMore": "Розкажіть детальніше",
    "feedback.placeholder": "Поділіться думками, пропозиціями або коментарями...",
    "feedback.submit": "Надіслати відгук",
    "feedback.submitting": "Надсилання...",
    "feedback.ratingRequired": "Виберіть оцінку",
    "feedback.success": "Дякуємо за ваш відгук!",
    "hero.tagline": "Відчуй мистецтво диму",
    "menu.ourSelection": "Наш вибір",
    "menu.curatedFlavors": "Вибрані смаки",
    "menu.singleFlavor": "Одиночний смак",
    "menu.signatureMixes": "Фірмові мікси",
    "menu.signature": "Фірмовий",
    "menu.extras": "Додатково",
    "menu.extrasSubtitle": "Напої та закуски",
    "menu.drinks": "Напої",
    "menu.snacks": "Закуски",
    "menu.addons": "Додатки",
    "strength.ultraLight": "Ультра легкий",
    "strength.light": "Легкий",
    "strength.medium": "Середній",
    "strength.boldStrong": "Міцний",
    "footer.inhale": "Вдихни",
    "footer.moment": "Мить",
    "footer.description": "Кожна затяжка розповідає історію. Нехай дим несе твої думки, поки захід сонця малює небо золотими відтінками.",
    "footer.tagline": "Преміум кальянний досвід",
    "auth.login": "Увійти",
    "auth.profile": "Профіль",
    "auth.level": "Рів.",
    "auth.admin": "Адмін",
    "auth.accounting": "Бухгалтерія",
    "auth.shishaMaster": "Кальянник",
    "auth.backToHome": "На головну",
    "auth.loginTitle": "Вхід",
    "auth.signupTitle": "Реєстрація",
    "auth.loginSubtitle": "Увійдіть у свій акаунт",
    "auth.signupSubtitle": "Створіть новий акаунт",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.loginButton": "Увійти",
    "auth.signupButton": "Зареєструватися",
    "auth.noAccount": "Немає акаунту?",
    "auth.haveAccount": "Вже є акаунт?",
    "auth.terms": "Натискаючи кнопку, ви погоджуєтесь з умовами використання",
    "auth.invalidEmail": "Невірний формат email",
    "auth.passwordMinLength": "Пароль повинен містити мінімум 6 символів",
    "auth.loginError": "Помилка входу",
    "auth.invalidCredentials": "Невірний email або пароль",
    "auth.error": "Помилка",
    "auth.welcome": "Ласкаво просимо!",
    "auth.loginSuccess": "Ви успішно увійшли в систему",
    "auth.signupError": "Помилка реєстрації",
    "auth.userExists": "Користувач з таким email вже існує",
    "auth.signupSuccess": "Реєстрація успішна!",
    "auth.checkEmail": "Перевірте вашу пошту для підтвердження акаунту",
    "auth.somethingWrong": "Щось пішло не так. Спробуйте пізніше.",
    
    // Admin/Dashboard
    "admin.panel": "Панель адміна",
    "admin.accounting": "Бухгалтерія",
    "admin.backToHome": "На головну",
    "admin.logout": "Вийти",
    "admin.overview": "Огляд",
    "admin.orders": "Замовлення",
    "admin.users": "Користувачі",
    "admin.totalOrders": "Всього замовлень",
    "admin.pending": "Очікують",
    "admin.paid": "Оплачено",
    "admin.today": "Сьогодні",
    "admin.totalRevenue": "Загальний дохід",
    "admin.todayRevenue": "Дохід сьогодні",
    "admin.totalHookahs": "Всього кальянів",
    "admin.totalUsers": "Користувачів",
    "admin.currentOrders": "Поточні замовлення",
    "admin.recentOrders": "Останні замовлення",
    "admin.allOrders": "Всі замовлення",
    "admin.noOrders": "Немає замовлень",
    "admin.hookahs": "кальян(ів)",
    "admin.room": "Кімната",
    "admin.guest": "Гість",
    "admin.markAsPaid": "Оплачено",
    "admin.cancel": "Скасувати",
    "admin.statusUpdated": "Статус оновлено",
    "admin.orderPaid": "Замовлення оплачено",
    "admin.orderCancelled": "Замовлення скасовано",
    "admin.confirmAction": "Підтвердіть дію",
    "admin.confirmPaidMessage": "Ви впевнені, що хочете позначити це замовлення як оплачене?",
    "admin.confirmCancelMessage": "Ви впевнені, що хочете скасувати це замовлення?",
    "admin.confirm": "Підтвердити",
    "admin.accessDenied": "Доступ заборонено",
    "admin.noPermission": "У вас немає прав для доступу до цієї сторінки",
    "admin.filterAll": "Всі",
    "admin.filterPending": "Очікують",
    "admin.filterPaid": "Оплачені",
    "admin.filterCancelled": "Скасовані",
    "admin.sortNewest": "Нові",
    "admin.sortOldest": "Старі",
    "admin.search": "Пошук за email, ім'ям або кімнатою...",
    "admin.total": "всього",
    "admin.exportCsv": "Експорт CSV",
    "admin.revenue": "Дохід",
    "admin.settings": "Налаштування",
    "admin.deliveryTime": "Час доставки",
    "admin.deliveryTimeDesc": "Максимальний час для доставки замовлення клієнту",
    "admin.minutes": "хвилин",
    "admin.saving": "Збереження...",
    "admin.settingsSaved": "Налаштування збережено",
    "admin.settingsError": "Помилка збереження налаштувань",
    
    // Roles
    "role.admin": "Адмін",
    "role.guest": "Гість",
    "role.shishaMaster": "Shisha Master",
    "role.accounting": "Бухгалтерія",
    
    // Shisha Master
    "shishaMaster.title": "Shisha Master",
    "shishaMaster.tabs.videos": "Відео інструкції",
    "shishaMaster.tabs.documents": "Документи",
    "shishaMaster.duration": "Тривалість",
    "shishaMaster.documentsTitle": "Інструкції та правила",
    "shishaMaster.download": "Завантажити",
    "shishaMaster.video.basics": "Основи приготування кальяну",
    "shishaMaster.video.coals": "Робота з вугіллям",
    "shishaMaster.video.flavors": "Змішування смаків",
    "shishaMaster.video.cleaning": "Чистка та обслуговування",
    "shishaMaster.doc.safetyRules": "Правила безпеки",
    "shishaMaster.doc.serviceStandards": "Стандарти обслуговування",
    "shishaMaster.doc.tobaccoGuide": "Посібник з тютюну",
    "shishaMaster.doc.equipmentManual": "Посібник з обладнання",
    "shishaMaster.doc.hygieneProtocol": "Протокол гігієни",
    "shishaMaster.orders.activeOrders": "Активні замовлення",
    "shishaMaster.orders.orders": "замовлень",
    "shishaMaster.orders.noOrders": "Немає активних замовлень",
    "shishaMaster.orders.timeRemaining": "Залишилось часу",
    "shishaMaster.orders.overdue": "ПРОСТРОЧЕНО",
    "shishaMaster.orders.markDelivered": "Доставлено",
    "shishaMaster.orders.cancelOrder": "Скасувати",
    "shishaMaster.orders.delivered": "Замовлення позначено як доставлене",
    "shishaMaster.orders.cancelled": "Замовлення скасовано",
    "shishaMaster.orders.error": "Помилка оновлення замовлення",
    "shishaMaster.orders.cancelOrderTitle": "Скасувати замовлення",
    "shishaMaster.orders.cancelOrderDesc": "Вкажіть причину скасування замовлення.",
    "shishaMaster.orders.cancelReasonPlaceholder": "Введіть причину скасування...",
    "shishaMaster.orders.cancelReason": "Причина скасування",
    "shishaMaster.orders.confirmCancel": "Підтвердити скасування",
    "shishaMaster.orders.history": "Історія",
    "shishaMaster.orders.noHistory": "Немає завершених замовлень",
    "shishaMaster.orders.statusDelivered": "Доставлено",
    "shishaMaster.orders.statusCancelled": "Скасовано",
    
    // Payment
    "payment.methods": "Способи оплати",
    "payment.bankTransfer": "Банківський переказ (IDR)",
    "payment.cash": "Готівкою на ресепшн",
    "payment.cashDescription": "Оплата готівкою на ресепшн",
    "payment.accountName": "Ім'я рахунку",
    "payment.bankName": "Банк",
    "payment.accountNumber": "Номер рахунку",
    "payment.copy": "Копіювати",
  },
  fr: {
    "hero.title": "CHICHA",
    "hero.subtitle": "MENU",
    "hero.tagline": "L'Art de la Fumée",
    "cart.submit": "Envoyer la commande",
    "nav.home": "Accueil",
    "nav.reservation": "Réservation",
    "nav.feedback": "Avis",
    "nav.history": "Historique",
    "nav.profile": "Profil",
    "reservation.title": "Réservation de fête",
    "reservation.subtitle": "Réservez votre expérience chicha",
    "reservation.selectDateTime": "Sélectionner date et heure",
    "reservation.date": "Date de réservation",
    "reservation.selectDate": "Sélectionner une date",
    "reservation.time": "Heure de réservation",
    "reservation.selectTime": "Sélectionner l'heure",
    "reservation.partySize": "Nombre d'invités",
    "reservation.hookahCount": "Nombre de chichas",
    "reservation.hookahCountDesc": "Combien de chichas avez-vous besoin pour votre fête?",
    "reservation.additionalInfo": "Informations supplémentaires",
    "reservation.phone": "Numéro de téléphone",
    "reservation.notes": "Notes",
    "reservation.notesPlaceholder": "Notes spéciales pour votre réservation",
    "reservation.specialRequests": "Demandes spéciales",
    "reservation.specialRequestsPlaceholder": "Saveurs préférées, préférences de places, etc.",
    "reservation.submit": "Réserver",
    "reservation.submitting": "Réservation...",
    "reservation.fillRequired": "Veuillez remplir tous les champs obligatoires",
    "reservation.success": "Réservation envoyée avec succès!",
    "reservation.error": "Échec de l'envoi de la réservation",
    "history.title": "Historique des commandes",
    "history.subtitle": "Vos commandes précédentes",
    "history.noOrders": "Aucune commande",
    "history.hookahs": "chicha(s)",
    "history.paid": "Payé",
    "history.pending": "En attente",
    "history.delivered": "Livré",
    "history.cancelled": "Annulé",
    "feedback.title": "Votre avis",
    "feedback.subtitle": "Aidez-nous à améliorer votre expérience",
    "feedback.rateExperience": "Évaluez votre expérience",
    "feedback.tellUsMore": "Dites-nous en plus",
    "feedback.placeholder": "Partagez vos pensées, suggestions ou commentaires...",
    "feedback.submit": "Envoyer l'avis",
    "feedback.submitting": "Envoi...",
    "feedback.ratingRequired": "Veuillez sélectionner une note",
    "feedback.success": "Merci pour votre avis!",
    "menu.ourSelection": "Notre Sélection",
    "menu.curatedFlavors": "Saveurs Raffinées",
    "menu.singleFlavor": "Saveur Unique",
    "menu.signatureMixes": "Mélanges Signature",
    "menu.signature": "Signature",
    "menu.extras": "Extras",
    "menu.extrasSubtitle": "Boissons & Collations",
    "menu.drinks": "Boissons",
    "menu.snacks": "Collations",
    "menu.addons": "Suppléments",
    "strength.ultraLight": "Ultra Léger",
    "strength.light": "Léger",
    "strength.medium": "Moyen",
    "strength.boldStrong": "Corsé",
    "footer.inhale": "Inspirez le",
    "footer.moment": "Moment",
    "footer.description": "Chaque bouffée raconte une histoire. Laissez la fumée emporter vos pensées tandis que le coucher de soleil peint le ciel de nuances dorées.",
    "footer.tagline": "Expérience Chicha Premium",
    "auth.login": "Connexion",
    "auth.profile": "Profil",
    "auth.level": "Niv.",
    "auth.admin": "Admin",
    "auth.accounting": "Comptabilité",
    "auth.shishaMaster": "Maître Chicha",
    "auth.backToHome": "Retour à l'accueil",
    "auth.loginTitle": "Connexion",
    "auth.signupTitle": "Inscription",
    "auth.loginSubtitle": "Connectez-vous à votre compte",
    "auth.signupSubtitle": "Créez un nouveau compte",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.loginButton": "Se connecter",
    "auth.signupButton": "S'inscrire",
    "auth.noAccount": "Pas de compte ?",
    "auth.haveAccount": "Déjà un compte ?",
    "auth.terms": "En cliquant sur le bouton, vous acceptez les conditions d'utilisation",
    "auth.invalidEmail": "Format d'email invalide",
    "auth.passwordMinLength": "Le mot de passe doit contenir au moins 6 caractères",
    "auth.loginError": "Erreur de connexion",
    "auth.invalidCredentials": "Email ou mot de passe incorrect",
    "auth.error": "Erreur",
    "auth.welcome": "Bienvenue !",
    "auth.loginSuccess": "Vous êtes connecté avec succès",
    "auth.signupError": "Erreur d'inscription",
    "auth.userExists": "Un utilisateur avec cet email existe déjà",
    "auth.signupSuccess": "Inscription réussie !",
    "auth.checkEmail": "Vérifiez votre email pour confirmer votre compte",
    "auth.somethingWrong": "Une erreur s'est produite. Veuillez réessayer plus tard.",
    
    // Admin/Dashboard
    "admin.panel": "Panneau Admin",
    "admin.accounting": "Comptabilité",
    "admin.backToHome": "Retour à l'accueil",
    "admin.logout": "Déconnexion",
    "admin.overview": "Aperçu",
    "admin.orders": "Commandes",
    "admin.users": "Utilisateurs",
    "admin.totalOrders": "Total des commandes",
    "admin.pending": "En attente",
    "admin.paid": "Payé",
    "admin.today": "Aujourd'hui",
    "admin.totalRevenue": "Revenu total",
    "admin.todayRevenue": "Revenu du jour",
    "admin.totalHookahs": "Total Chichas",
    "admin.totalUsers": "Utilisateurs",
    "admin.currentOrders": "Commandes en cours",
    "admin.recentOrders": "Commandes récentes",
    "admin.allOrders": "Toutes les commandes",
    "admin.noOrders": "Aucune commande",
    "admin.hookahs": "chicha(s)",
    "admin.room": "Chambre",
    "admin.guest": "Invité",
    "admin.markAsPaid": "Marquer payé",
    "admin.cancel": "Annuler",
    "admin.statusUpdated": "Statut mis à jour",
    "admin.orderPaid": "Commande marquée payée",
    "admin.orderCancelled": "Commande annulée",
    "admin.confirmAction": "Confirmer l'action",
    "admin.confirmPaidMessage": "Êtes-vous sûr de vouloir marquer cette commande comme payée ?",
    "admin.confirmCancelMessage": "Êtes-vous sûr de vouloir annuler cette commande ?",
    "admin.confirm": "Confirmer",
    "admin.accessDenied": "Accès refusé",
    "admin.noPermission": "Vous n'avez pas la permission d'accéder à cette page",
    "admin.filterAll": "Tous",
    "admin.filterPending": "En attente",
    "admin.filterPaid": "Payés",
    "admin.filterCancelled": "Annulés",
    "admin.sortNewest": "Plus récent",
    "admin.sortOldest": "Plus ancien",
    "admin.search": "Rechercher par email, nom ou chambre...",
    "admin.total": "total",
    "admin.exportCsv": "Exporter CSV",
    "admin.revenue": "Revenu",
    "admin.settings": "Paramètres",
    "admin.deliveryTime": "Temps de livraison",
    "admin.deliveryTimeDesc": "Temps maximum pour livrer la commande au client",
    "admin.minutes": "minutes",
    "admin.saving": "Enregistrement...",
    "admin.settingsSaved": "Paramètres enregistrés",
    "admin.settingsError": "Erreur d'enregistrement",
    
    // Roles
    "role.admin": "Admin",
    "role.guest": "Invité",
    "role.shishaMaster": "Shisha Master",
    "role.accounting": "Comptabilité",
    
    // Shisha Master
    "shishaMaster.title": "Shisha Master",
    "shishaMaster.tabs.videos": "Vidéos d'instruction",
    "shishaMaster.tabs.documents": "Documents",
    "shishaMaster.duration": "Durée",
    "shishaMaster.documentsTitle": "Instructions et règles",
    "shishaMaster.download": "Télécharger",
    "shishaMaster.video.basics": "Bases de la préparation chicha",
    "shishaMaster.video.coals": "Travail avec le charbon",
    "shishaMaster.video.flavors": "Guide de mélange des saveurs",
    "shishaMaster.video.cleaning": "Nettoyage et entretien",
    "shishaMaster.doc.safetyRules": "Règles de sécurité",
    "shishaMaster.doc.serviceStandards": "Normes de service",
    "shishaMaster.doc.tobaccoGuide": "Guide du tabac",
    "shishaMaster.doc.equipmentManual": "Manuel d'équipement",
    "shishaMaster.doc.hygieneProtocol": "Protocole d'hygiène",
    "shishaMaster.orders.activeOrders": "Commandes actives",
    "shishaMaster.orders.orders": "commandes",
    "shishaMaster.orders.noOrders": "Aucune commande active",
    "shishaMaster.orders.timeRemaining": "Temps restant",
    "shishaMaster.orders.overdue": "EN RETARD",
    "shishaMaster.orders.markDelivered": "Livré",
    "shishaMaster.orders.cancelOrder": "Annuler",
    "shishaMaster.orders.delivered": "Commande marquée livrée",
    "shishaMaster.orders.cancelled": "Commande annulée",
    "shishaMaster.orders.error": "Erreur de mise à jour",
    "shishaMaster.orders.cancelOrderTitle": "Annuler la commande",
    "shishaMaster.orders.cancelOrderDesc": "Veuillez fournir une raison d'annulation.",
    "shishaMaster.orders.cancelReasonPlaceholder": "Entrez la raison...",
    "shishaMaster.orders.cancelReason": "Raison d'annulation",
    "shishaMaster.orders.confirmCancel": "Confirmer l'annulation",
    "shishaMaster.orders.history": "Historique",
    "shishaMaster.orders.noHistory": "Aucune commande terminée",
    "shishaMaster.orders.statusDelivered": "Livré",
    "shishaMaster.orders.statusCancelled": "Annulé",
    
    // Payment
    "payment.methods": "Modes de paiement",
    "payment.bankTransfer": "Virement bancaire (IDR)",
    "payment.cash": "Espèces à la réception",
    "payment.cashDescription": "Payer en espèces à la réception",
    "payment.accountName": "Nom du compte",
    "payment.bankName": "Banque",
    "payment.accountNumber": "Numéro de compte",
    "payment.copy": "Copier",
  },
  hi: {
    "hero.title": "हुक्का",
    "hero.subtitle": "मेन्यू",
    "cart.submit": "ऑर्डर भेजें",
    "nav.home": "होम",
    "nav.reservation": "आरक्षण",
    "nav.feedback": "प्रतिक्रिया",
    "nav.history": "इतिहास",
    "nav.profile": "प्रोफ़ाइल",
    "reservation.title": "पार्टी आरक्षण",
    "reservation.subtitle": "अपना हुक्का अनुभव बुक करें",
    "reservation.selectDateTime": "तारीख और समय चुनें",
    "reservation.date": "आरक्षण तिथि",
    "reservation.selectDate": "तारीख चुनें",
    "reservation.time": "आरक्षण समय",
    "reservation.selectTime": "आरक्षण समय चुनें",
    "reservation.partySize": "मेहमानों की संख्या",
    "reservation.hookahCount": "हुक्के की संख्या",
    "reservation.hookahCountDesc": "आपकी पार्टी के लिए कितने हुक्के चाहिए?",
    "reservation.additionalInfo": "अतिरिक्त जानकारी",
    "reservation.phone": "फ़ोन नंबर",
    "reservation.notes": "नोट्स",
    "reservation.notesPlaceholder": "अपने आरक्षण के लिए विशेष नोट्स",
    "reservation.specialRequests": "विशेष अनुरोध",
    "reservation.specialRequestsPlaceholder": "पसंदीदा स्वाद, बैठने की प्राथमिकताएं, आदि।",
    "reservation.submit": "आरक्षण करें",
    "reservation.submitting": "बुक हो रहा है...",
    "reservation.fillRequired": "कृपया सभी आवश्यक फ़ील्ड भरें",
    "reservation.success": "आरक्षण सफलतापूर्वक जमा!",
    "reservation.error": "आरक्षण जमा करने में विफल",
    "history.title": "ऑर्डर इतिहास",
    "history.subtitle": "आपके पिछले ऑर्डर",
    "history.noOrders": "अभी तक कोई ऑर्डर नहीं",
    "history.hookahs": "हुक्का",
    "history.paid": "भुगतान किया",
    "history.pending": "लंबित",
    "history.delivered": "डिलीवर किया",
    "history.cancelled": "रद्द",
    "feedback.title": "आपकी प्रतिक्रिया",
    "feedback.subtitle": "हमें अपना अनुभव बेहतर बनाने में मदद करें",
    "feedback.rateExperience": "अपने अनुभव को रेट करें",
    "feedback.tellUsMore": "और बताएं",
    "feedback.placeholder": "अपने विचार, सुझाव या टिप्पणियां साझा करें...",
    "feedback.submit": "प्रतिक्रिया भेजें",
    "feedback.submitting": "भेज रहा है...",
    "feedback.ratingRequired": "कृपया रेटिंग चुनें",
    "feedback.success": "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    "hero.tagline": "धुएं की कला का अनुभव करें",
    "menu.ourSelection": "हमारा चयन",
    "menu.curatedFlavors": "चुने हुए स्वाद",
    "menu.singleFlavor": "सिंगल फ्लेवर",
    "menu.signatureMixes": "सिग्नेचर मिक्स",
    "menu.signature": "सिग्नेचर",
    "menu.extras": "अतिरिक्त",
    "menu.extrasSubtitle": "पेय और स्नैक्स",
    "menu.drinks": "पेय पदार्थ",
    "menu.snacks": "स्नैक्स",
    "menu.addons": "ऐड-ऑन",
    "strength.ultraLight": "अल्ट्रा लाइट",
    "strength.light": "लाइट",
    "strength.medium": "मध्यम",
    "strength.boldStrong": "स्ट्रॉन्ग",
    "footer.inhale": "इस पल को",
    "footer.moment": "महसूस करें",
    "footer.description": "हर कश एक कहानी कहता है। धुएं को अपने विचारों को ले जाने दें जब सूर्यास्त आकाश को सुनहरे रंगों में रंग देता है।",
    "footer.tagline": "प्रीमियम हुक्का अनुभव",
    "auth.login": "लॉगिन",
    "auth.profile": "प्रोफ़ाइल",
    "auth.level": "स्तर",
    "auth.admin": "एडमिन",
    "auth.accounting": "लेखांकन",
    "auth.shishaMaster": "हुक्का मास्टर",
    "auth.backToHome": "होम पर वापस जाएं",
    "auth.loginTitle": "लॉगिन",
    "auth.signupTitle": "साइन अप",
    "auth.loginSubtitle": "अपने खाते में लॉगिन करें",
    "auth.signupSubtitle": "नया खाता बनाएं",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.loginButton": "लॉगिन करें",
    "auth.signupButton": "साइन अप करें",
    "auth.noAccount": "खाता नहीं है?",
    "auth.haveAccount": "पहले से खाता है?",
    "auth.terms": "बटन पर क्लिक करके, आप उपयोग की शर्तों से सहमत होते हैं",
    "auth.invalidEmail": "अमान्य ईमेल प्रारूप",
    "auth.passwordMinLength": "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
    "auth.loginError": "लॉगिन त्रुटि",
    "auth.invalidCredentials": "गलत ईमेल या पासवर्ड",
    "auth.error": "त्रुटि",
    "auth.welcome": "स्वागत है!",
    "auth.loginSuccess": "आपने सफलतापूर्वक लॉगिन किया",
    "auth.signupError": "पंजीकरण त्रुटि",
    "auth.userExists": "इस ईमेल वाला उपयोगकर्ता पहले से मौजूद है",
    "auth.signupSuccess": "पंजीकरण सफल!",
    "auth.checkEmail": "अपने खाते की पुष्टि के लिए अपना ईमेल जांचें",
    "auth.somethingWrong": "कुछ गलत हो गया। कृपया बाद में पुनः प्रयास करें।",
    
    // Admin/Dashboard
    "admin.panel": "एडमिन पैनल",
    "admin.accounting": "लेखांकन",
    "admin.backToHome": "होम पर वापस",
    "admin.logout": "लॉगआउट",
    "admin.overview": "अवलोकन",
    "admin.orders": "ऑर्डर",
    "admin.users": "उपयोगकर्ता",
    "admin.totalOrders": "कुल ऑर्डर",
    "admin.pending": "लंबित",
    "admin.paid": "भुगतान किया",
    "admin.today": "आज",
    "admin.totalRevenue": "कुल राजस्व",
    "admin.todayRevenue": "आज का राजस्व",
    "admin.totalHookahs": "कुल हुक्के",
    "admin.totalUsers": "कुल उपयोगकर्ता",
    "admin.currentOrders": "वर्तमान ऑर्डर",
    "admin.recentOrders": "हाल के ऑर्डर",
    "admin.allOrders": "सभी ऑर्डर",
    "admin.noOrders": "कोई ऑर्डर नहीं",
    "admin.hookahs": "हुक्का",
    "admin.room": "कमरा",
    "admin.guest": "अतिथि",
    "admin.markAsPaid": "भुगतान किया",
    "admin.cancel": "रद्द करें",
    "admin.statusUpdated": "स्थिति अपडेट की गई",
    "admin.orderPaid": "ऑर्डर भुगतान के रूप में चिह्नित",
    "admin.orderCancelled": "ऑर्डर रद्द किया गया",
    "admin.confirmAction": "क्रिया की पुष्टि करें",
    "admin.confirmPaidMessage": "क्या आप सुनिश्चित हैं कि इस ऑर्डर को भुगतान के रूप में चिह्नित करना चाहते हैं?",
    "admin.confirmCancelMessage": "क्या आप सुनिश्चित हैं कि इस ऑर्डर को रद्द करना चाहते हैं?",
    "admin.confirm": "पुष्टि करें",
    "admin.accessDenied": "पहुंच अस्वीकृत",
    "admin.noPermission": "आपके पास इस पेज तक पहुंचने की अनुमति नहीं है",
    "admin.search": "ईमेल, नाम या कमरे से खोजें...",
    "admin.total": "कुल",
    "admin.exportCsv": "CSV निर्यात करें",
    "admin.revenue": "राजस्व",
    "admin.settings": "सेटिंग्स",
    "admin.deliveryTime": "डिलीवरी समय",
    "admin.deliveryTimeDesc": "ग्राहक को ऑर्डर डिलीवर करने का अधिकतम समय",
    "admin.minutes": "मिनट",
    "admin.saving": "सहेज रहा है...",
    "admin.settingsSaved": "सेटिंग्स सहेजी गईं",
    "admin.settingsError": "सेटिंग्स सहेजने में त्रुटि",
    
    // Roles
    "role.admin": "एडमिन",
    "role.guest": "अतिथि",
    "role.shishaMaster": "शीशा मास्टर",
    "role.accounting": "लेखांकन",
    
    // Shisha Master
    "shishaMaster.title": "शीशा मास्टर",
    "shishaMaster.tabs.videos": "वीडियो निर्देश",
    "shishaMaster.tabs.documents": "दस्तावेज़",
    "shishaMaster.duration": "अवधि",
    "shishaMaster.documentsTitle": "निर्देश और नियम",
    "shishaMaster.download": "डाउनलोड",
    "shishaMaster.video.basics": "हुक्का तैयारी की मूल बातें",
    "shishaMaster.video.coals": "कोयले के साथ काम करना",
    "shishaMaster.video.flavors": "स्वाद मिश्रण गाइड",
    "shishaMaster.video.cleaning": "सफाई और रखरखाव",
    "shishaMaster.doc.safetyRules": "सुरक्षा नियम",
    "shishaMaster.doc.serviceStandards": "सेवा मानक",
    "shishaMaster.doc.tobaccoGuide": "तंबाकू हैंडलिंग गाइड",
    "shishaMaster.doc.equipmentManual": "उपकरण मैनुअल",
    "shishaMaster.doc.hygieneProtocol": "स्वच्छता प्रोटोकॉल",
    "shishaMaster.orders.activeOrders": "सक्रिय ऑर्डर",
    "shishaMaster.orders.orders": "ऑर्डर",
    "shishaMaster.orders.noOrders": "कोई सक्रिय ऑर्डर नहीं",
    "shishaMaster.orders.timeRemaining": "शेष समय",
    "shishaMaster.orders.overdue": "देरी",
    "shishaMaster.orders.markDelivered": "डिलीवर किया",
    "shishaMaster.orders.cancelOrder": "रद्द करें",
    "shishaMaster.orders.delivered": "ऑर्डर डिलीवर चिह्नित",
    "shishaMaster.orders.cancelled": "ऑर्डर रद्द",
    "shishaMaster.orders.error": "ऑर्डर अपडेट त्रुटि",
    "shishaMaster.orders.cancelOrderTitle": "ऑर्डर रद्द करें",
    "shishaMaster.orders.cancelOrderDesc": "कृपया रद्द करने का कारण दें।",
    "shishaMaster.orders.cancelReasonPlaceholder": "रद्द करने का कारण दर्ज करें...",
    "shishaMaster.orders.cancelReason": "रद्द करने का कारण",
    "shishaMaster.orders.confirmCancel": "रद्द की पुष्टि करें",
    "shishaMaster.orders.history": "इतिहास",
    "shishaMaster.orders.noHistory": "कोई पूर्ण ऑर्डर नहीं",
    "shishaMaster.orders.statusDelivered": "डिलीवर किया गया",
    "shishaMaster.orders.statusCancelled": "रद्द किया गया",
    
    // Payment
    "payment.methods": "भुगतान के तरीके",
    "payment.bankTransfer": "बैंक ट्रांसफर (IDR)",
    "payment.cash": "रिसेप्शन पर नकद",
    "payment.cashDescription": "रिसेप्शन डेस्क पर नकद भुगतान करें",
    "payment.accountName": "खाता नाम",
    "payment.bankName": "बैंक",
    "payment.accountNumber": "खाता संख्या",
    "payment.copy": "कॉपी",
  },
  zh: {
    "hero.title": "水烟",
    "hero.subtitle": "菜单",
    "cart.submit": "发送订单",
    "nav.home": "首页",
    "nav.reservation": "预订",
    "nav.feedback": "反馈",
    "nav.history": "历史",
    "nav.profile": "个人",
    "reservation.title": "派对预订",
    "reservation.subtitle": "预订您的水烟体验",
    "reservation.selectDateTime": "选择日期和时间",
    "reservation.date": "预订日期",
    "reservation.selectDate": "选择日期",
    "reservation.time": "预订时间",
    "reservation.selectTime": "选择预订时间",
    "reservation.partySize": "宾客人数",
    "reservation.hookahCount": "水烟数量",
    "reservation.hookahCountDesc": "您的派对需要多少个水烟?",
    "reservation.additionalInfo": "附加信息",
    "reservation.phone": "电话号码",
    "reservation.notes": "备注",
    "reservation.notesPlaceholder": "预订的特别说明",
    "reservation.specialRequests": "特殊要求",
    "reservation.specialRequestsPlaceholder": "喜欢的口味、座位偏好等",
    "reservation.submit": "提交预订",
    "reservation.submitting": "提交中...",
    "reservation.fillRequired": "请填写所有必填字段",
    "reservation.success": "预订提交成功!",
    "reservation.error": "预订提交失败",
    "history.title": "订单历史",
    "history.subtitle": "您的历史订单",
    "history.noOrders": "暂无订单",
    "history.hookahs": "个水烟",
    "history.paid": "已支付",
    "history.pending": "待处理",
    "history.delivered": "已送达",
    "history.cancelled": "已取消",
    "feedback.title": "您的反馈",
    "feedback.subtitle": "帮助我们改进您的体验",
    "feedback.rateExperience": "评价您的体验",
    "feedback.tellUsMore": "告诉我们更多",
    "feedback.placeholder": "分享您的想法、建议或评论...",
    "feedback.submit": "提交反馈",
    "feedback.submitting": "提交中...",
    "feedback.ratingRequired": "请选择评分",
    "feedback.success": "感谢您的反馈!",
    "hero.tagline": "体验烟雾艺术",
    "menu.ourSelection": "我们的精选",
    "menu.curatedFlavors": "精选口味",
    "menu.singleFlavor": "单一口味",
    "menu.signatureMixes": "招牌混合",
    "menu.signature": "招牌",
    "menu.extras": "额外项目",
    "menu.extrasSubtitle": "饮料和小吃",
    "menu.drinks": "饮料",
    "menu.snacks": "小吃",
    "menu.addons": "附加项",
    "strength.ultraLight": "超轻",
    "strength.light": "轻度",
    "strength.medium": "中度",
    "strength.boldStrong": "浓烈",
    "footer.inhale": "感受这",
    "footer.moment": "一刻",
    "footer.description": "每一口都讲述一个故事。让烟雾带走你的思绪，当夕阳将天空染成金色。",
    "footer.tagline": "高端水烟体验",
    "auth.login": "登录",
    "auth.profile": "个人资料",
    "auth.level": "等级",
    "auth.admin": "管理",
    "auth.accounting": "财务",
    "auth.shishaMaster": "水烟师",
    "auth.backToHome": "返回首页",
    "auth.loginTitle": "登录",
    "auth.signupTitle": "注册",
    "auth.loginSubtitle": "登录您的账户",
    "auth.signupSubtitle": "创建新账户",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.loginButton": "登录",
    "auth.signupButton": "注册",
    "auth.noAccount": "没有账户？",
    "auth.haveAccount": "已有账户？",
    "auth.terms": "点击按钮即表示您同意使用条款",
    "auth.invalidEmail": "邮箱格式无效",
    "auth.passwordMinLength": "密码至少需要6个字符",
    "auth.loginError": "登录错误",
    "auth.invalidCredentials": "邮箱或密码错误",
    "auth.error": "错误",
    "auth.welcome": "欢迎！",
    "auth.loginSuccess": "您已成功登录",
    "auth.signupError": "注册错误",
    "auth.userExists": "该邮箱的用户已存在",
    "auth.signupSuccess": "注册成功！",
    "auth.checkEmail": "请检查您的邮箱以确认账户",
    "auth.somethingWrong": "出现问题，请稍后重试。",
    
    // Admin/Dashboard
    "admin.panel": "管理面板",
    "admin.accounting": "财务",
    "admin.backToHome": "返回首页",
    "admin.logout": "退出登录",
    "admin.overview": "概览",
    "admin.orders": "订单",
    "admin.users": "用户",
    "admin.totalOrders": "总订单数",
    "admin.pending": "待处理",
    "admin.paid": "已支付",
    "admin.today": "今日",
    "admin.totalRevenue": "总收入",
    "admin.todayRevenue": "今日收入",
    "admin.totalHookahs": "总水烟数",
    "admin.totalUsers": "用户数",
    "admin.currentOrders": "当前订单",
    "admin.recentOrders": "最近订单",
    "admin.allOrders": "所有订单",
    "admin.noOrders": "没有订单",
    "admin.hookahs": "水烟",
    "admin.room": "房间",
    "admin.guest": "客人",
    "admin.markAsPaid": "标记已付",
    "admin.cancel": "取消",
    "admin.statusUpdated": "状态已更新",
    "admin.orderPaid": "订单已标记为已付",
    "admin.orderCancelled": "订单已取消",
    "admin.confirmAction": "确认操作",
    "admin.confirmPaidMessage": "您确定要将此订单标记为已付款吗？",
    "admin.confirmCancelMessage": "您确定要取消此订单吗？",
    "admin.confirm": "确认",
    "admin.accessDenied": "拒绝访问",
    "admin.noPermission": "您没有权限访问此页面",
    "admin.search": "按邮箱、姓名或房间搜索...",
    "admin.total": "总计",
    "admin.exportCsv": "导出CSV",
    "admin.revenue": "收入",
    "admin.settings": "设置",
    "admin.deliveryTime": "送达时间",
    "admin.deliveryTimeDesc": "订单送达客户的最长时间",
    "admin.minutes": "分钟",
    "admin.saving": "保存中...",
    "admin.settingsSaved": "设置已保存",
    "admin.settingsError": "保存设置出错",
    
    // Roles
    "role.admin": "管理员",
    "role.guest": "客人",
    "role.shishaMaster": "水烟师",
    "role.accounting": "财务",
    
    // Shisha Master
    "shishaMaster.title": "水烟师",
    "shishaMaster.tabs.videos": "视频教程",
    "shishaMaster.tabs.documents": "文档",
    "shishaMaster.duration": "时长",
    "shishaMaster.documentsTitle": "说明和规则",
    "shishaMaster.download": "下载",
    "shishaMaster.video.basics": "水烟准备基础",
    "shishaMaster.video.coals": "炭火使用",
    "shishaMaster.video.flavors": "口味混合指南",
    "shishaMaster.video.cleaning": "清洁与维护",
    "shishaMaster.doc.safetyRules": "安全规则",
    "shishaMaster.doc.serviceStandards": "服务标准",
    "shishaMaster.doc.tobaccoGuide": "烟草处理指南",
    "shishaMaster.doc.equipmentManual": "设备手册",
    "shishaMaster.doc.hygieneProtocol": "卫生规程",
    "shishaMaster.orders.activeOrders": "活跃订单",
    "shishaMaster.orders.orders": "订单",
    "shishaMaster.orders.noOrders": "没有活跃订单",
    "shishaMaster.orders.timeRemaining": "剩余时间",
    "shishaMaster.orders.overdue": "超时",
    "shishaMaster.orders.markDelivered": "已送达",
    "shishaMaster.orders.cancelOrder": "取消",
    "shishaMaster.orders.delivered": "订单已标记为送达",
    "shishaMaster.orders.cancelled": "订单已取消",
    "shishaMaster.orders.error": "更新订单错误",
    "shishaMaster.orders.cancelOrderTitle": "取消订单",
    "shishaMaster.orders.cancelOrderDesc": "请提供取消原因。",
    "shishaMaster.orders.cancelReasonPlaceholder": "输入取消原因...",
    "shishaMaster.orders.cancelReason": "取消原因",
    "shishaMaster.orders.confirmCancel": "确认取消",
    "shishaMaster.orders.history": "历史记录",
    "shishaMaster.orders.noHistory": "暂无已完成订单",
    "shishaMaster.orders.statusDelivered": "已送达",
    "shishaMaster.orders.statusCancelled": "已取消",
    
    // Payment
    "payment.methods": "支付方式",
    "payment.bankTransfer": "银行转账 (IDR)",
    "payment.cash": "前台现金支付",
    "payment.cashDescription": "在前台用现金支付",
    "payment.accountName": "账户名称",
    "payment.bankName": "银行",
    "payment.accountNumber": "账号",
    "payment.copy": "复制",
  },
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
