import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ru" | "id" | "uk" | "fr" | "hi" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Hero
    "hero.title": "SHISHA",
    "hero.subtitle": "MENU",
    "hero.tagline": "Experience the Art of Smoke",
    
    // Menu
    "menu.ourSelection": "Our Selection",
    "menu.curatedFlavors": "Curated Flavors",
    "menu.singleFlavor": "Single Flavor",
    "menu.signatureMixes": "Signature Mixes",
    "menu.signature": "Signature",
    "menu.addedToCart": "Added to cart!",
    "menu.loginToOrder": "Please login to order",
    "menu.clickToAdd": "Click + to add items to your order",
    "menu.loginToOrderHint": "Login to start ordering",
    "menu.extras": "Extras",
    "menu.extrasSubtitle": "Drinks & Snacks",
    "menu.drinks": "Beverages",
    "menu.snacks": "Snacks",
    "menu.addons": "Add-ons",
    
    // Cart
    "cart.title": "Your Order",
    "cart.empty": "Your cart is empty",
    "cart.total": "Total",
    "cart.placeOrder": "Place Order",
    "cart.clear": "Clear cart",
    "cart.loginRequired": "Please login to place an order",
    "cart.emptyCart": "Your cart is empty",
    "cart.orderSuccess": "Order placed successfully!",
    "cart.orderError": "Failed to place order",
    "cart.loginToOrder": "Please login to place an order",
    "cart.login": "Login",
    "cart.payNow": "Pay Now",
    "cart.payLater": "Pay Later",
    "cart.paymentError": "Payment failed. Please try again.",
    
    // Order Confirmation
    "order.confirmed": "Order Confirmed!",
    "order.thankYou": "Thank you for your order",
    "order.orderNumber": "Order Number",
    "order.estimatedTime": "Estimated Wait Time",
    "order.approx": "Approx.",
    "order.minutes": "minutes",
    "order.summary": "Order Summary",
    "order.backToMenu": "Back to Menu",
    "order.viewProfile": "View Profile",
    "order.notification": "We'll notify you when your order is ready",
    "order.deliveryTo": "Delivery to room",
    "order.wrongRoom": "If the room number is incorrect, please update it",
    "order.updateRoom": "Update room number",
    "order.noRoom": "Room number not specified",
    "order.addRoomHint": "Add your room number for delivery",
    "order.addRoom": "Add room number",
    
    // Strength levels
    "strength.ultraLight": "Ultra Light",
    "strength.light": "Light",
    "strength.medium": "Medium",
    "strength.boldStrong": "Bold Strong",
    
    // Footer
    "footer.inhale": "Inhale the",
    "footer.moment": "Moment",
    "footer.description": "Each puff tells a story. Let the smoke carry your thoughts as the sunset paints the sky in shades of gold.",
    "footer.tagline": "Premium Shisha Experience",
    
    // Auth
    "auth.login": "Login",
    "auth.profile": "Profile",
    "auth.level": "Lvl.",
    "auth.admin": "Admin",
    "auth.backToHome": "Back to Home",
    "auth.loginTitle": "Login",
    "auth.signupTitle": "Sign Up",
    "auth.loginSubtitle": "Log in to your account",
    "auth.signupSubtitle": "Create a new account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.loginButton": "Log In",
    "auth.signupButton": "Sign Up",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    "auth.terms": "By clicking the button, you agree to the terms of use",
    "auth.invalidEmail": "Invalid email format",
    "auth.passwordMinLength": "Password must be at least 6 characters",
    "auth.loginError": "Login Error",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.error": "Error",
    "auth.welcome": "Welcome!",
    "auth.loginSuccess": "You have successfully logged in",
    "auth.signupError": "Registration Error",
    "auth.userExists": "A user with this email already exists",
    "auth.signupSuccess": "Registration successful!",
    "auth.checkEmail": "Check your email to confirm your account",
    "auth.somethingWrong": "Something went wrong. Please try again later.",
  },
  ru: {
    "hero.title": "КАЛЬЯН",
    "hero.subtitle": "МЕНЮ",
    "hero.tagline": "Искусство дыма",
    "menu.ourSelection": "Наш выбор",
    "menu.curatedFlavors": "Избранные вкусы",
    "menu.singleFlavor": "Одиночный вкус",
    "menu.signatureMixes": "Фирменные миксы",
    "menu.signature": "Фирменный",
    "menu.addedToCart": "Добавлено в корзину!",
    "menu.loginToOrder": "Войдите, чтобы сделать заказ",
    "menu.clickToAdd": "Нажмите + чтобы добавить в заказ",
    "menu.loginToOrderHint": "Войдите, чтобы начать заказ",
    "menu.extras": "Дополнительно",
    "menu.extrasSubtitle": "Напитки и закуски",
    "menu.drinks": "Напитки",
    "menu.snacks": "Закуски",
    "menu.addons": "Дополнения",
    "cart.title": "Ваш заказ",
    "cart.empty": "Корзина пуста",
    "cart.total": "Итого",
    "cart.placeOrder": "Оформить заказ",
    "cart.clear": "Очистить корзину",
    "cart.loginRequired": "Войдите, чтобы оформить заказ",
    "cart.emptyCart": "Корзина пуста",
    "cart.orderSuccess": "Заказ успешно оформлен!",
    "cart.orderError": "Ошибка оформления заказа",
    "cart.loginToOrder": "Войдите, чтобы оформить заказ",
    "cart.login": "Войти",
    "cart.payNow": "Оплатить сейчас",
    "cart.payLater": "Оплатить позже",
    "cart.paymentError": "Ошибка оплаты. Попробуйте ещё раз.",
    "order.confirmed": "Заказ подтверждён!",
    "order.thankYou": "Спасибо за ваш заказ",
    "order.orderNumber": "Номер заказа",
    "order.estimatedTime": "Ожидаемое время",
    "order.approx": "Примерно",
    "order.minutes": "минут",
    "order.summary": "Состав заказа",
    "order.backToMenu": "Вернуться к меню",
    "order.viewProfile": "Мой профиль",
    "order.notification": "Мы уведомим вас, когда заказ будет готов",
    "order.deliveryTo": "Доставка в комнату",
    "order.wrongRoom": "Если номер комнаты неверный, пожалуйста, обновите его",
    "order.updateRoom": "Изменить номер комнаты",
    "order.noRoom": "Номер комнаты не указан",
    "order.addRoomHint": "Добавьте номер комнаты для доставки",
    "order.addRoom": "Указать номер комнаты",
    "strength.ultraLight": "Ультра лёгкий",
    "strength.light": "Лёгкий",
    "strength.medium": "Средний",
    "strength.boldStrong": "Крепкий",
    "footer.inhale": "Вдохни",
    "footer.moment": "Момент",
    "footer.description": "Каждая затяжка рассказывает историю. Пусть дым унесёт твои мысли, пока закат окрашивает небо в золотые оттенки.",
    "footer.tagline": "Премиум кальянный опыт",
    "auth.login": "Войти",
    "auth.profile": "Профиль",
    "auth.level": "Ур.",
    "auth.admin": "Админ",
    "auth.backToHome": "На главную",
    "auth.loginTitle": "Вход",
    "auth.signupTitle": "Регистрация",
    "auth.loginSubtitle": "Войдите в свой аккаунт",
    "auth.signupSubtitle": "Создайте новый аккаунт",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.loginButton": "Войти",
    "auth.signupButton": "Зарегистрироваться",
    "auth.noAccount": "Нет аккаунта?",
    "auth.haveAccount": "Уже есть аккаунт?",
    "auth.terms": "Нажимая кнопку, вы соглашаетесь с условиями использования",
    "auth.invalidEmail": "Неверный формат email",
    "auth.passwordMinLength": "Пароль должен содержать минимум 6 символов",
    "auth.loginError": "Ошибка входа",
    "auth.invalidCredentials": "Неверный email или пароль",
    "auth.error": "Ошибка",
    "auth.welcome": "Добро пожаловать!",
    "auth.loginSuccess": "Вы успешно вошли в систему",
    "auth.signupError": "Ошибка регистрации",
    "auth.userExists": "Пользователь с таким email уже существует",
    "auth.signupSuccess": "Регистрация успешна!",
    "auth.checkEmail": "Проверьте вашу почту для подтверждения аккаунта",
    "auth.somethingWrong": "Что-то пошло не так. Попробуйте позже.",
  },
  id: {
    "hero.title": "SHISHA",
    "hero.subtitle": "MENU",
    "hero.tagline": "Rasakan Seni Asap",
    "menu.ourSelection": "Pilihan Kami",
    "menu.curatedFlavors": "Rasa Terpilih",
    "menu.singleFlavor": "Rasa Tunggal",
    "menu.signatureMixes": "Campuran Khas",
    "menu.signature": "Khas",
    "menu.extras": "Tambahan",
    "menu.extrasSubtitle": "Minuman & Makanan Ringan",
    "menu.drinks": "Minuman",
    "menu.snacks": "Makanan Ringan",
    "menu.addons": "Tambahan",
    "strength.ultraLight": "Ultra Ringan",
    "strength.light": "Ringan",
    "strength.medium": "Sedang",
    "strength.boldStrong": "Kuat",
    "footer.inhale": "Hirup",
    "footer.moment": "Momen",
    "footer.description": "Setiap hisapan menceritakan sebuah kisah. Biarkan asap membawa pikiranmu saat matahari terbenam melukis langit dengan warna emas.",
    "footer.tagline": "Pengalaman Shisha Premium",
    "auth.login": "Masuk",
    "auth.profile": "Profil",
    "auth.level": "Lvl.",
    "auth.admin": "Admin",
    "auth.backToHome": "Kembali ke Beranda",
    "auth.loginTitle": "Masuk",
    "auth.signupTitle": "Daftar",
    "auth.loginSubtitle": "Masuk ke akun Anda",
    "auth.signupSubtitle": "Buat akun baru",
    "auth.email": "Email",
    "auth.password": "Kata Sandi",
    "auth.loginButton": "Masuk",
    "auth.signupButton": "Daftar",
    "auth.noAccount": "Belum punya akun?",
    "auth.haveAccount": "Sudah punya akun?",
    "auth.terms": "Dengan mengklik tombol, Anda menyetujui ketentuan penggunaan",
    "auth.invalidEmail": "Format email tidak valid",
    "auth.passwordMinLength": "Kata sandi minimal 6 karakter",
    "auth.loginError": "Kesalahan Masuk",
    "auth.invalidCredentials": "Email atau kata sandi salah",
    "auth.error": "Kesalahan",
    "auth.welcome": "Selamat Datang!",
    "auth.loginSuccess": "Anda berhasil masuk",
    "auth.signupError": "Kesalahan Pendaftaran",
    "auth.userExists": "Pengguna dengan email ini sudah ada",
    "auth.signupSuccess": "Pendaftaran berhasil!",
    "auth.checkEmail": "Periksa email Anda untuk mengonfirmasi akun",
    "auth.somethingWrong": "Terjadi kesalahan. Silakan coba lagi nanti.",
  },
  uk: {
    "hero.title": "КАЛЬЯН",
    "hero.subtitle": "МЕНЮ",
    "hero.tagline": "Відчуй мистецтво диму",
    "menu.ourSelection": "Наш вибір",
    "menu.curatedFlavors": "Вибрані смаки",
    "menu.singleFlavor": "Одиночний смак",
    "menu.signatureMixes": "Фірмові мікси",
    "menu.signature": "Фірмовий",
    "menu.extras": "Додатково",
    "menu.extrasSubtitle": "Напої та закуски",
    "menu.drinks": "Напої",
    "menu.snacks": "Закуски",
    "menu.addons": "Додатки",
    "strength.ultraLight": "Ультра легкий",
    "strength.light": "Легкий",
    "strength.medium": "Середній",
    "strength.boldStrong": "Міцний",
    "footer.inhale": "Вдихни",
    "footer.moment": "Мить",
    "footer.description": "Кожна затяжка розповідає історію. Нехай дим несе твої думки, поки захід сонця малює небо золотими відтінками.",
    "footer.tagline": "Преміум кальянний досвід",
    "auth.login": "Увійти",
    "auth.profile": "Профіль",
    "auth.level": "Рів.",
    "auth.admin": "Адмін",
    "auth.backToHome": "На головну",
    "auth.loginTitle": "Вхід",
    "auth.signupTitle": "Реєстрація",
    "auth.loginSubtitle": "Увійдіть у свій акаунт",
    "auth.signupSubtitle": "Створіть новий акаунт",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.loginButton": "Увійти",
    "auth.signupButton": "Зареєструватися",
    "auth.noAccount": "Немає акаунту?",
    "auth.haveAccount": "Вже є акаунт?",
    "auth.terms": "Натискаючи кнопку, ви погоджуєтесь з умовами використання",
    "auth.invalidEmail": "Невірний формат email",
    "auth.passwordMinLength": "Пароль повинен містити мінімум 6 символів",
    "auth.loginError": "Помилка входу",
    "auth.invalidCredentials": "Невірний email або пароль",
    "auth.error": "Помилка",
    "auth.welcome": "Ласкаво просимо!",
    "auth.loginSuccess": "Ви успішно увійшли в систему",
    "auth.signupError": "Помилка реєстрації",
    "auth.userExists": "Користувач з таким email вже існує",
    "auth.signupSuccess": "Реєстрація успішна!",
    "auth.checkEmail": "Перевірте вашу пошту для підтвердження акаунту",
    "auth.somethingWrong": "Щось пішло не так. Спробуйте пізніше.",
  },
  fr: {
    "hero.title": "CHICHA",
    "hero.subtitle": "MENU",
    "hero.tagline": "L'Art de la Fumée",
    "menu.ourSelection": "Notre Sélection",
    "menu.curatedFlavors": "Saveurs Raffinées",
    "menu.singleFlavor": "Saveur Unique",
    "menu.signatureMixes": "Mélanges Signature",
    "menu.signature": "Signature",
    "menu.extras": "Extras",
    "menu.extrasSubtitle": "Boissons & Collations",
    "menu.drinks": "Boissons",
    "menu.snacks": "Collations",
    "menu.addons": "Suppléments",
    "strength.ultraLight": "Ultra Léger",
    "strength.light": "Léger",
    "strength.medium": "Moyen",
    "strength.boldStrong": "Corsé",
    "footer.inhale": "Inspirez le",
    "footer.moment": "Moment",
    "footer.description": "Chaque bouffée raconte une histoire. Laissez la fumée emporter vos pensées tandis que le coucher de soleil peint le ciel de nuances dorées.",
    "footer.tagline": "Expérience Chicha Premium",
    "auth.login": "Connexion",
    "auth.profile": "Profil",
    "auth.level": "Niv.",
    "auth.admin": "Admin",
    "auth.backToHome": "Retour à l'accueil",
    "auth.loginTitle": "Connexion",
    "auth.signupTitle": "Inscription",
    "auth.loginSubtitle": "Connectez-vous à votre compte",
    "auth.signupSubtitle": "Créez un nouveau compte",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.loginButton": "Se connecter",
    "auth.signupButton": "S'inscrire",
    "auth.noAccount": "Pas de compte ?",
    "auth.haveAccount": "Déjà un compte ?",
    "auth.terms": "En cliquant sur le bouton, vous acceptez les conditions d'utilisation",
    "auth.invalidEmail": "Format d'email invalide",
    "auth.passwordMinLength": "Le mot de passe doit contenir au moins 6 caractères",
    "auth.loginError": "Erreur de connexion",
    "auth.invalidCredentials": "Email ou mot de passe incorrect",
    "auth.error": "Erreur",
    "auth.welcome": "Bienvenue !",
    "auth.loginSuccess": "Vous êtes connecté avec succès",
    "auth.signupError": "Erreur d'inscription",
    "auth.userExists": "Un utilisateur avec cet email existe déjà",
    "auth.signupSuccess": "Inscription réussie !",
    "auth.checkEmail": "Vérifiez votre email pour confirmer votre compte",
    "auth.somethingWrong": "Une erreur s'est produite. Veuillez réessayer plus tard.",
  },
  hi: {
    "hero.title": "हुक्का",
    "hero.subtitle": "मेन्यू",
    "hero.tagline": "धुएं की कला का अनुभव करें",
    "menu.ourSelection": "हमारा चयन",
    "menu.curatedFlavors": "चुने हुए स्वाद",
    "menu.singleFlavor": "सिंगल फ्लेवर",
    "menu.signatureMixes": "सिग्नेचर मिक्स",
    "menu.signature": "सिग्नेचर",
    "menu.extras": "अतिरिक्त",
    "menu.extrasSubtitle": "पेय और स्नैक्स",
    "menu.drinks": "पेय पदार्थ",
    "menu.snacks": "स्नैक्स",
    "menu.addons": "ऐड-ऑन",
    "strength.ultraLight": "अल्ट्रा लाइट",
    "strength.light": "लाइट",
    "strength.medium": "मध्यम",
    "strength.boldStrong": "स्ट्रॉन्ग",
    "footer.inhale": "इस पल को",
    "footer.moment": "महसूस करें",
    "footer.description": "हर कश एक कहानी कहता है। धुएं को अपने विचारों को ले जाने दें जब सूर्यास्त आकाश को सुनहरे रंगों में रंग देता है।",
    "footer.tagline": "प्रीमियम हुक्का अनुभव",
    "auth.login": "लॉगिन",
    "auth.profile": "प्रोफ़ाइल",
    "auth.level": "स्तर",
    "auth.admin": "एडमिन",
    "auth.backToHome": "होम पर वापस जाएं",
    "auth.loginTitle": "लॉगिन",
    "auth.signupTitle": "साइन अप",
    "auth.loginSubtitle": "अपने खाते में लॉगिन करें",
    "auth.signupSubtitle": "नया खाता बनाएं",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.loginButton": "लॉगिन करें",
    "auth.signupButton": "साइन अप करें",
    "auth.noAccount": "खाता नहीं है?",
    "auth.haveAccount": "पहले से खाता है?",
    "auth.terms": "बटन पर क्लिक करके, आप उपयोग की शर्तों से सहमत होते हैं",
    "auth.invalidEmail": "अमान्य ईमेल प्रारूप",
    "auth.passwordMinLength": "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
    "auth.loginError": "लॉगिन त्रुटि",
    "auth.invalidCredentials": "गलत ईमेल या पासवर्ड",
    "auth.error": "त्रुटि",
    "auth.welcome": "स्वागत है!",
    "auth.loginSuccess": "आपने सफलतापूर्वक लॉगिन किया",
    "auth.signupError": "पंजीकरण त्रुटि",
    "auth.userExists": "इस ईमेल वाला उपयोगकर्ता पहले से मौजूद है",
    "auth.signupSuccess": "पंजीकरण सफल!",
    "auth.checkEmail": "अपने खाते की पुष्टि के लिए अपना ईमेल जांचें",
    "auth.somethingWrong": "कुछ गलत हो गया। कृपया बाद में पुनः प्रयास करें।",
  },
  zh: {
    "hero.title": "水烟",
    "hero.subtitle": "菜单",
    "hero.tagline": "体验烟雾艺术",
    "menu.ourSelection": "我们的精选",
    "menu.curatedFlavors": "精选口味",
    "menu.singleFlavor": "单一口味",
    "menu.signatureMixes": "招牌混合",
    "menu.signature": "招牌",
    "menu.extras": "额外项目",
    "menu.extrasSubtitle": "饮料和小吃",
    "menu.drinks": "饮料",
    "menu.snacks": "小吃",
    "menu.addons": "附加项",
    "strength.ultraLight": "超轻",
    "strength.light": "轻度",
    "strength.medium": "中度",
    "strength.boldStrong": "浓烈",
    "footer.inhale": "感受这",
    "footer.moment": "一刻",
    "footer.description": "每一口都讲述一个故事。让烟雾带走你的思绪，当夕阳将天空染成金色。",
    "footer.tagline": "高端水烟体验",
    "auth.login": "登录",
    "auth.profile": "个人资料",
    "auth.level": "等级",
    "auth.admin": "管理",
    "auth.backToHome": "返回首页",
    "auth.loginTitle": "登录",
    "auth.signupTitle": "注册",
    "auth.loginSubtitle": "登录您的账户",
    "auth.signupSubtitle": "创建新账户",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.loginButton": "登录",
    "auth.signupButton": "注册",
    "auth.noAccount": "没有账户？",
    "auth.haveAccount": "已有账户？",
    "auth.terms": "点击按钮即表示您同意使用条款",
    "auth.invalidEmail": "邮箱格式无效",
    "auth.passwordMinLength": "密码至少需要6个字符",
    "auth.loginError": "登录错误",
    "auth.invalidCredentials": "邮箱或密码错误",
    "auth.error": "错误",
    "auth.welcome": "欢迎！",
    "auth.loginSuccess": "您已成功登录",
    "auth.signupError": "注册错误",
    "auth.userExists": "该邮箱的用户已存在",
    "auth.signupSuccess": "注册成功！",
    "auth.checkEmail": "请检查您的邮箱以确认账户",
    "auth.somethingWrong": "出现问题，请稍后重试。",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
